desci-models/src/ResearchObject.ts
Asana ticket: [link](https://app.asana.com/0/1203951109818008/1204229226239257)
=> Add ResearchObjectV1Authors interface

desci-models/src/ResearchObject.ts, desci-models/tests/ResearchObject.test.ts, desci-server/src/services/ipfs.ts, desci-server/src/services/manifestSpec.ts, desci-server/test/integration/ipfs.test.ts, docker-compose.test.yml
Asana ticket: [ticket_link](https://app.asana.com/0/1203951109818008/1204229226239257)
Add role field to research object author interface
=> Add role to research object author interface

desci-server/package.json, desci-server/prisma/migrations/20230405222251_private_share_table/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/datasets/retrieve.ts, desci-server/src/controllers/nodes/index.ts, desci-server/src/controllers/nodes/share.ts, desci-server/src/controllers/nodes/show.ts, desci-server/src/controllers/nodes/versionDetails.ts, desci-server/src/routes/v1/datasets.ts, desci-server/src/routes/v1/nodes.ts, desci-server/yarn.lock
Asana ticket: [https://app.asana.com/0/1203951109818008/1204320644940350](https://app.asana.com/0/1203951109818008/1204320644940350)
- This PR has a database migration included
- Private share table goes from share uuid -> node uuid
- Implement apis to create, verify and revoke share Link
- Implement public versions of the `nodes/*` and `retrieveTree/*` apis with shareId params for authentication
- Run database Migration
- Starts node server
- Test on `nodes-web/privates-share` branch
=> Private share

desci-server/prisma/migrations/20230416160624_ls/migration.sql, desci-server/prisma/migrations/20230416164438_add_external_to_publicrefs/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/datasets/update.ts, desci-server/src/controllers/datasets/upload.ts, desci-server/src/controllers/nodes/draftCreate.ts, desci-server/src/middleware/upgradeManifest.ts, desci-server/src/scripts/upgradeManifests.ts, desci-server/src/services/dataService.ts, desci-server/src/services/ipfs.ts, desci-server/src/services/nodeManager.ts, desci-server/src/utils.ts, desci-server/src/utils/driveUtils.ts, desci-server/test/integration/ipfs.test.ts
External CIDs couldn't be linked to a research object
Adds external CID linking support to research objects
closes  #60
=> External Cid support

desci-server/src/controllers/data/update.ts
Couldn't create empty directories to categorize your research artifacts
Update controller updated to support creating new empty dirs
Create directories using the Add button select menu in drive
=> Drive/New Directories

desci-server/src/utils/driveUtils.ts
Changes backend instances of subType to subtype
=> subType -> subtype

desci-models/src/transformers/RoCrateTransformer.ts, desci-models/tests/example-data/exampleNodeToRoCrate.json, desci-server/prisma/migrations/20230429214452_make_public_refs_option_user_and_version/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/data/update.ts, desci-server/src/controllers/nodes/nodesCover.ts, desci-server/src/controllers/nodes/publish.ts, desci-server/src/controllers/nodes/show.ts, desci-server/src/controllers/raw/resolve.ts, desci-server/src/services/estuary.ts, desci-server/src/services/ipfs.ts, desci-server/src/services/nodeManager.ts, desci-server/src/services/user.ts, desci-server/src/utils.ts, desci-server/src/utils/driveUtils.ts
=> fix publish flow

desci-models/src/transformers/RoCrateTransformer.ts, desci-models/tests/example-data/exampleNodeToRoCrate.json, desci-server/src/utils/driveUtils.ts
Fixes problem with ro-crate jsonld output for dpid links
=> Fix ro crate dpid

desci-server/src/services/ipfs.ts
=> tree call optimizations

desci-models/package.json, desci-models/src/transformers/RoCrateTransformer.ts, desci-models/tests/example-data/exampleNodeToRoCrate.json, desci-models/tests/example-data/exampleNodeWithAuthors.json, desci-models/tests/transformers/RoCrateTransformer.test.ts
=> json-ld enhancements

.github/workflows/build-and-test.yaml, .github/workflows/build-server.yaml, desci-server/src/index.ts
logs were too verbose for express HTTP requests, causing scrolling beyond reason
Use a serializer from pino-http lib
Restart your server
None, just need to make sure betterstack logs don't get truncated
=> stop logging so much in local dev mode

desci-server/src/controllers/data/retrieve.ts
=> fix pubTree return indenting

desci-server/src/controllers/data/retrieve.ts
Cached tree was returning incorrectly
Fixed returned cached tree
=> Fix pubTree api

desci-server/.eslintrc.js, desci-server/src/controllers/data/delete.ts, desci-server/src/controllers/data/move.ts, desci-server/src/controllers/data/rename.ts, desci-server/src/controllers/data/retrieve.ts, desci-server/src/controllers/data/update.ts, desci-server/src/services/ipfs.ts, desci-server/src/utils.ts
Inefficient functions within data flow operations
- Pass across the major data flow controllers, improving efficiency of functions on larger data
- Fixed repo upload crashing on larger uploads
- Cleaned up and simplified segments of logic within the controllers
- Few potential path collision bugs patched
- Rename bug retrieving non existing file crash fixed
=> Data optimizations

desci-server/kubernetes/deployment_dev.yaml, desci-server/src/scripts/fetch-drive-tree-for-cache.ts, desci-server/src/services/nodeManager.ts
we were logging too much when uploading data, causing problems when navigating logs
Stop logging excess file info
=> Fix publish ext

desci-server/src/utils/dataRefTools.ts
ext cids published werent marked as external, causing failed publish
mark external cids as external
=> Ext cid pub fix

desci-models/README.md
=> update desci-models readme

desci-server/src/controllers/data/rename.ts, desci-server/src/controllers/data/update.ts
Inefficiencies in the update/rename controller when working with large data, rendering those operations unusable when data gets large enough.
Turned quadratic operations into linear operations by leveraging hashmaps, significantly reducing the time complexity of those controllers when dealing with larger data
=> Data/Controller Improvements

desci-models/src/trees/treeTools.ts, desci-models/src/trees/treeTypes.ts, desci-server/src/controllers/data/diff.ts, desci-server/src/controllers/data/utils.ts, desci-server/src/redisClient.ts, desci-server/src/routes/v1/data.ts, desci-server/src/utils/diffUtils.ts
Closes #101
No ability to see the difference between two different node versions
- Added a calculated diff for data tree differences
- Added tree stats (node size diff for now)
=> Tree Diffing API

desci-models/package.json
Bump the version after adding containsComponents to a DriveObject
=> Models bump after containsComponents added

desci-server/src/controllers/data/updateExternalCid.ts, desci-server/src/services/ipfs.ts
fix the fix
https://github.com/desci-labs/nodes/pull/117
=> Tree improvements

desci-models/src/trees/treeTools.ts, desci-models/src/trees/treeTypes.ts, desci-server/src/controllers/data/diff.ts, desci-server/src/utils/diffUtils.ts
- Lack of size breakdown per components
- expanded containsComponents metadata, added sizes per component
=> Aggregate sizes

desci-models/package.json
Models version bump after containsComponents expansion
=> Bump models ver

desci-server/src/services/ipfs.ts
Increase resolution timeout for the internal ipfs cluster
=> Increase timeout

desci-server/src/controllers/data/update.ts, desci-server/src/services/ipfs.ts, desci-server/src/utils.ts
=> Revert "Memory fix for repo data uploads"

desci-server/src/controllers/auth/logout.ts, desci-server/src/controllers/auth/magic.ts, desci-server/src/middleware/checkJwt.ts, desci-server/src/middleware/ensureUser.ts
- Cookies cross origin handling adjusted
- Logout route logic added
=> Adjust cookies, add logout

desci-server/src/controllers/auth/magic.ts
- Unable to test local dev frontend using a prod backend as they're on different domains and cookies don't get sent up.
- Add a deliberate dev flag to the magic link controller to only return a localhost cookie if requested, to mitigate potential security risks.
=> Dev Testing Auth

desci-server/src/controllers/auth/magic.ts
- Cookie being discarded by client because server returning address different to domain set on the cookie
- Strip the cookie of the domain property
=> Dev cookie fix

desci-models/package.json, desci-models/src/ResearchObject.ts
Add `rects: []` field to `ResearchObjectComponentAnnotation` to support multi-line text highlights
=> Add support for rects (text-annotations)

desci-server/prisma/migrations/20230924044837_authtokensource/migration.sql, desci-server/prisma/migrations/20230924045154_authsourcenotnull/migration.sql
migration issue due to not null source col and no default
modify migration to allow null field for authtoken source
run migration
=> modify nullable auth token source

desci-server/src/controllers/nodes/consent.ts, desci-server/src/controllers/proxy/orcidProfile.ts, desci-server/src/controllers/users/associateWallet.ts, desci-server/src/routes/v1/services.ts, desci-server/src/routes/v1/users.ts, desci-server/src/services/user.ts
- no way to go from did:pkh -> orcid
- store association of orcid did:pkh to user
- write the did:pkh to orcid profile as Public Key external ID
=> write DID to orcid + create API for orcid-did profile

desci-server/src/controllers/auth/logout.ts, desci-server/src/routes/v1/auth.ts
promote main, address logout problems
=> promote main

desci-server/src/index.ts
=> app.listen only once

desci-server/src/controllers/data/rename.ts, desci-server/src/controllers/data/retrieve.ts, desci-server/src/controllers/data/update.ts, desci-server/src/controllers/data/updateExternalCid.ts, desci-server/src/controllers/nodes/draftCreate.ts, desci-server/src/controllers/raw/resolve.ts, desci-server/src/utils/generateArweaveKeys.ts
undo the bug caused by bulk find and replace of slash '/' with '../../' that messed up logic throughought the backend for purposes of ESM compilation
=> undo the bug caused by bulk find and replace

.github/workflows/build-server.yaml, desci-contracts/yarn.lock, desci-server/src/controllers/auth/magic.ts, desci-server/src/services/auth.ts, desci-server/src/services/ipfs.ts, desci-server/src/services/user.ts
did not ignore email case for sending email verification
ignore email case
=> hotfix email verification

desci-server/package.json, desci-server/prisma/migrations/20240110020737_add_community_and_items_feed_and_endorsements/migration.sql, desci-server/prisma/migrations/20240110044029_dpid10/migration.sql, desci-server/prisma/migrations/20240110050930_endorse_dpid/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/nodes/feed.ts, desci-server/src/routes/v1/nodes.ts, desci-server/src/scripts/endorseDpid.ts
allow users to endorse nodes
run script to endorse node, makes it appear on an API Node Feed endpoint called `api/v1/nodes/feed`
```yarn script:endorse-dpid 46                   ```
=> allow for endorsement of nodes

desci-server/src/utils/draftTreeUtils.ts
- Module handling changes introduced a bug in a package that we import
- Small fix to import, ty @m0ar
=> Package import fix

desci-server/package.json, desci-server/src/controllers/nodes/documents.ts, desci-server/src/lib/PostgresStorageAdapter.ts, desci-server/src/repo.ts, desci-server/src/services/manifestRepo.ts, desci-server/yarn.lock
- Upgrade Automerge version to latest @2.1.10
- Auto recovery for incorrect automerge document.uuid field
- Fix potential error pitfalls
=> Automerge Integration improvement

desci-models/package.json, desci-models/src/ResearchObject.ts
=> Update subtypes in PdfComponent, ExternalLinkComponent, DataComponent and CodeComponent.

.vscode/launch.json, desci-server/nodemon.json, desci-server/package.json, desci-server/src/controllers/auth/login.ts, desci-server/src/controllers/data/delete.ts, desci-server/src/controllers/data/move.ts, desci-server/src/controllers/data/rename.ts, desci-server/src/controllers/data/update.ts, desci-server/src/controllers/data/updateExternalCid.ts, desci-server/src/middleware/permissions.ts, desci-server/src/routes/v1/auth.ts, desci-server/src/services/data/externalCidProcessing.ts, desci-server/src/services/data/externalUrlProcessing.ts, desci-server/src/services/data/processing.ts, desci-server/src/services/manifestRepo.ts, desci-server/src/services/user.ts, desci-server/src/utils/driveUtils.ts, desci-server/test/integration/data.test.ts
- Further efforts to make automerge integration resilient
=> Error recovery

.ceramicTemplate.config.json, ceramic.Dockerfile, interpolateConfigVars.sh
Adds a dockerfile which wraps the ceramic image, interpolating envvars into a template config file at container start. I do not know if this is very smart or very stupid, let's find out :fire:
=> Ceramic Dockerfile with config interpolation

desci-server/package.json, desci-server/src/scripts/seedSocialData.ts
- Issue with auto seed script not running for already instantiated dbs
- Separate the seed script to be able to run it manually
=> Communities seed script changes

desci-server/src/controllers/communities/util.ts
Fix Incorrect node version displayed in community curated and radar feeds
=> Fix Node version on radar/curated feeds

desci-server/src/controllers/attestations/comments.ts, desci-server/src/controllers/attestations/verification.ts, desci-server/src/routes/v1/attestations/index.ts, desci-server/src/routes/v1/attestations/schema.ts, desci-server/src/services/Attestation.ts
- Make necessary updates needed to support V1 of comments api
- Add validation for post and get api requests using zod
=> Feat: comment/annotation api integration V1

desci-server/src/controllers/attestations/claims.ts, desci-server/src/controllers/attestations/comments.ts, desci-server/src/controllers/attestations/reactions.ts, desci-server/src/controllers/attestations/verification.ts, desci-server/src/internal.ts, desci-server/src/middleware/validator.ts, desci-server/src/routes/v1/attestations/index.ts, desci-server/src/routes/v1/attestations/schema.ts, desci-server/src/services/Attestation.ts
- Add validation to social apis resources
- format error shape to be more informative
=> Api validation and Error formatting

desci-server/src/controllers/attestations/recommendations.ts, desci-server/src/controllers/communities/feed.ts, desci-server/src/controllers/communities/list.ts, desci-server/src/controllers/communities/radar.ts, desci-server/src/data/communities.json, desci-server/src/routes/v1/attestations/index.ts, desci-server/src/scripts/DESTRUCTIVE-clear-social-data.ts, desci-server/src/scripts/seed-social-data.ts, desci-server/src/services/Attestation.ts, desci-server/src/services/Communities.ts
Implement shared entry attestations feature, update apis, database queries, attestation and community services, refactor seed script
=> Feat: Shared Entry attestations across all communities 

desci-server/src/controllers/attestations/recommendations.ts, desci-server/src/controllers/communities/feed.ts, desci-server/src/controllers/communities/list.ts, desci-server/src/controllers/communities/util.ts, desci-server/src/scripts/seed-social-data.ts, desci-server/src/services/Attestation.ts, desci-server/src/services/Communities.ts
- Update query to pull published node version count while claiming an attestation
=> Postfixes for Social features

nodes-media/Dockerfile, nodes-media/package.json, nodes-media/tsconfig.json, nodes-media/yarn.lock
Couldn't resist a bit of dep cleanup :hand_over_mouth:
=> nodes-media: bump node base image

reverse-proxy/kubernetes/deployment_dev.yaml, reverse-proxy/kubernetes/deployment_prod.yaml, reverse-proxy/kubernetes/deployment_staging.yaml
_Here I go again on my ooown_ :notes: :snake:
=> reverse-proxy: fix broken between ingress and load balancer

desci-server/package.json, desci-server/prisma/migrations/20240421124358_orcid_record_putcodes/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/attestations/verification.ts, desci-server/src/controllers/auth/orcid.ts, desci-server/src/controllers/nodes/publish.ts, desci-server/src/services/Attestation.ts, desci-server/src/services/orcid.ts, desci-server/test/integration/Attestation.test.ts, desci-server/yarn.lock
- Reflect Research node details on author's orcid work record after publish 
- Update ORCID work record to reflect verified protected claims on author's node
=> ORCID record(works) integration

desci-server/src/controllers/attestations/verification.ts, desci-server/src/services/orcid.ts, desci-server/src/services/user.ts
=> Revert "Orcid authtoken refresh"

desci-server/src/services/user.ts
- Update last PR to fix hanging test
=> fix: hanging tests

desci-server/scripts/be-node-dev.sh
Adjusted port in the backend startup script, reverted it to what it has been for a long time.
This configuration works for a fresh startup.
=> Local dev deployment fixes

desci-server/src/controllers/attestations/claims.ts, desci-server/src/controllers/attestations/verification.ts, desci-server/src/controllers/nodes/consent.ts, desci-server/src/services/orcid.ts, desci-server/test/integration/Attestation.test.ts
- Notify community members when protected attestations are claimed
- Fix: double claim on active attestations claimed on previous node versions
=> Desci foundation features/enhancements

desci-server/src/services/orcid.ts
=> Auth refresh token debug

desci-server/kubernetes/deployment_dev.yaml, desci-server/kubernetes/deployment_prod.yaml, desci-server/kubernetes/deployment_staging.yaml
=> Claim email logs and remove unused configs

desci-server/src/controllers/attestations/claims.ts
=> Capture failure

desci-server/prisma/migrations/20240510003939_orcid_put_record_update/migration.sql, desci-server/prisma/migrations/20240510020627_orcid_putcode_table/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/attestations/verification.ts, desci-server/src/services/Attestation.ts, desci-server/src/services/orcid.ts, desci-server/src/theGraph.ts
- orcid attestation writing structure and put code tracking db table schema update
=> ORCID attestation writing structure

desci-server/src/controllers/attestations/claims.ts, desci-server/src/controllers/attestations/verification.ts
=> Non blocking after effects for mailing and orcid writing

desci-server/src/controllers/attestations/claims.ts
=> fix: api code paths build error

desci-server/src/services/orcid.ts
- Inline documentation of Orcid writing service
=> Chore: document orcid api service class, methods and utils

desci-server/scripts/be-node-dev.sh, desci-server/src/controllers/auth/orcid.ts, desci-server/src/services/user.ts
- insert ORCID auth token on every fresh login attempt
=> Fix ORCID auth token entries

desci-server/src/services/orcid.ts
- External IDs not unique in some cases
=> fix: unique external-ids for work record

desci-server/src/services/orcid.ts
- Orcid writing bugs and invalid data writing
- Remove unnecessary fields 
- Only generate contributor data once for all records
=> fix: Orcid schema and updates to OrcidApiService implementation

desci-server/kubernetes/deployment_dev.yaml, desci-server/kubernetes/deployment_prod.yaml, desci-server/kubernetes/deployment_staging.yaml, desci-server/src/services/orcid.ts
Add DPID_URL_OVERRIDE to k8s config
Dpid url override if necessary
=> DPID url config 

desci-server/kubernetes/deployment_dev.yaml, desci-server/kubernetes/deployment_prod.yaml, desci-server/kubernetes/deployment_staging.yaml, desci-server/src/services/orcid.ts
Reverts desci-labs/nodes#345
Vault has been updated with these variables, so this should work now :crossed_fingers:
=> Revert "Revert "DPID url config ""

.env.example, .env.test, .vscode/settings.json, desci-server/kubernetes/deployment_dev.yaml, desci-server/kubernetes/deployment_prod.yaml, desci-server/kubernetes/deployment_staging.yaml, desci-server/prisma/migrations/20240604115330_doi_record_table/migration.sql, desci-server/prisma/migrations/20240604123832_add_doi_records_table/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/doi/check.ts, desci-server/src/controllers/doi/index.ts, desci-server/src/controllers/doi/mint.ts, desci-server/src/controllers/nodes/prepublish.ts, desci-server/src/core/ApiError.ts, desci-server/src/core/ApiResponse.ts, desci-server/src/core/doi/error.ts, desci-server/src/internal.ts, desci-server/src/middleware/authorisation.ts, desci-server/src/redisClient.ts, desci-server/src/routes/v1/doi.ts, desci-server/src/routes/v1/index.ts, desci-server/src/services/Attestation.ts, desci-server/src/services/Doi.ts, desci-server/src/services/crossRef/client.ts, desci-server/src/services/crossRef/definitions.ts, desci-server/src/services/crossRef/utils.ts, desci-server/src/services/index.ts, desci-server/src/types/ProcessEnv.d.ts
- DOI_PREFIX=https://doi.org/10.62891
- CROSSREF_API=https://api.crossref.org
- CROSSREF_API_KEY
- CROSSREF_EMAIL
- Updates to DOI minting workflow
- Implement CrossRef Api client
=> DOI Workflow and CrossRef Api Client Implementation

desci-server/src/core/ApiResponse.ts
=> remove unnecessary message from api res

desci-server/src/controllers/nodes/contributions/getNodeContributions.ts, desci-server/src/controllers/nodes/publish.ts, desci-server/src/services/Contributors.ts, desci-server/src/services/PublishServices.ts, desci-server/src/templates/emails/NodeUpdated.tsx, desci-server/src/templates/emails/utils/emailRenderer.tsx
- Handles email sending to all contributors on publish events
=> Prepub emails

desci-server/Makefile, desci-server/src/controllers/nodes/createDpid.ts, desci-server/src/services/PublishPackage.ts, desci-server/src/utils.ts
- Enabled draft cover generations, using placeholder links
- Fixed some local devex issues with recent changes in dev
- Updated badge hyperlinks to use the new attestation routing
Should be merged with this frontend PR to enable draft prepub distribution pdf previews https://github.com/desci-labs/nodes-web-v2/pull/769
=> Prepub API changes

desci-models/package.json, desci-models/src/automerge.ts, desci-repo/package.json, desci-repo/src/services/manifestRepo.ts, desci-repo/src/validators/schema.ts, desci-repo/src/validators/test/schema.spec.ts, desci-repo/yarn.lock, desci-server/package.json, desci-server/yarn.lock
- Add support for  multiple contributors to automerge repo service
- Upgrade desci-models
=> Model upgrade and support multiple authors in repo service

desci-server/src/controllers/communities/feed.ts, desci-server/src/controllers/communities/util.ts, desci-server/src/services/Communities.ts
- Community radar/curation node resolver should resolve last published manifest
=> Node Radar/Explore are pulling draft manifest

desci-server/src/controllers/communities/util.ts
=> fix: draft node data leak

desci-media-isolated/package-lock.json, desci-media-isolated/package.json, desci-server/src/controllers/nodes/contributions/prepubEmail.ts, desci-server/src/controllers/nodes/frontmatterPreview.ts
- dotless UUID search in email controller failed
- pino pretty needed to be added in the media server
=> ensureDotInUuid in email fixed

desci-server/src/controllers/nodes/frontmatterPreview.ts
=> remove bug

desci-server/src/controllers/nodes/doi.ts
- Extract paper abstract metadata from open alex abstract inverted index
=> Improve metadata extraction

desci-server/prisma/migrations/20240703141325_add_dpid_unique_doi_uuid_to_submission_queue/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/doi/check.ts, desci-server/src/controllers/doi/mint.ts, desci-server/src/services/Attestation.ts, desci-server/src/services/Doi.ts, desci-server/src/services/crossRef/client.ts, desci-server/src/services/orcid.ts, desci-server/src/utils.ts
- Only create DOI after crossref confirmation
- Fix issues with xml template and label contributor sequences correctly
- Upgrade database schema
=> Fix doi registration

desci-server/src/controllers/nodes/contributions/create.ts, desci-server/src/controllers/nodes/contributions/update.ts, dockerDev.sh
- --parallel flag for builds prevented local dev startup - possibly environment dependent, removed for time being
- Fixed inviteSent flag in contributionMap endpoint
- Optional silent contributor invite added to contributor add endpoint for use in prepub flow
=> Squash bugs

desci-server/src/controllers/nodes/doi.ts, desci-server/src/services/AutomatedMetadata.ts
- Set fallback ipfs resolver
- Set default grobid metadata response
=> Prevent future crash in Grobid integration

desci-server/src/controllers/attestations/recommendations.ts, desci-server/src/services/Attestation.ts, desci-server/test/integration/Attestation.test.ts
- Recommended attestations list is grouped by attestations
=> Update RecommendedAttestations return data model

desci-server/src/controllers/doi/mint.ts
=> Return early if submission has been processed successfully before

desci-server/src/controllers/nodes/checkNodeAccess.ts
- Private share broke with node resolution changes
- Fixed new access APIs and code flow for resolution to fix private sharing nodes
Should be merged in with frontend fix:  https://github.com/desci-labs/nodes-web-v2/pull/811
=> Priv share fix backend

.gitignore, desci-server/src/services/Attestation.ts, desci-server/src/services/Communities.ts, desci-server/test/integration/Attestation.test.ts
=> Fix Community radar listing 

desci-contracts/subgraph/subgraph.sepoliaProd.yaml, desci-media-isolated/kubernetes/deployment_prod.yaml, desci-server/kubernetes/deployment_prod.yaml
=> config fixes for prod

desci-server/src/services/Attestation.ts
=> show all entry attestations

desci-server/prisma/migrations/20240808102242_/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/nodes/bookmarks/create.ts, desci-server/src/controllers/nodes/bookmarks/delete.ts, desci-server/src/controllers/nodes/bookmarks/index.ts, desci-server/src/routes/v1/nodes.ts
- No way to shortlist nodes
- Table created for bookmarking nodes
- Adds endpoints for adding/removing bookmarked nodes
- Adds endpoint to retrieve bookmarked collections
Contains migrations!!!
=> Bookmarking nodes

desci-server/src/controllers/raw/versions.ts, desci-server/src/theGraph.ts
fixing a bug in a fix, where we just dropped other uuid's instead :bubble_tea:
=> server: fix a bug in history where certain uuids are dropped from lookups

desci-server/src/controllers/attestations/claims.ts, desci-server/src/services/Attestation.ts, desci-server/src/services/PublishServices.ts
Confusion between attestationId/claimId/nodeAttestationId
should be the final fix 🙏
=> Proposed defer email fix

desci-models/package.json, desci-models/src/ResearchObject.ts, desci-models/src/automerge.ts, desci-models/yarn.lock, desci-repo/package.json, desci-repo/src/services/manifestRepo.ts, desci-repo/src/validators/schema.ts, desci-repo/src/validators/test/schema.spec.ts, desci-repo/yarn.lock, package-lock.json
Closes #428
- Add reference field to Research object model
-  Update automerge library to support reference actions
-  Update actions schema and add tests
- Bump desci-models package
=> ResearchObject Model References field

desci-server/src/services/ElasticSearchService.ts
- Updated denormalized works index to the latest one
- Re-enabled author citation counts in scoring algo
- Added a time decay function to make more recent works more prominent in the scoring algo
=> Es index updates

desci-server/src/controllers/auth/logout.ts, desci-server/src/middleware/checkJwt.ts, desci-server/src/utils/sendCookie.ts
debug cookie issue in prod
set samesite to lax to see if cookie issues resolve
=> adjust cookie setting

desci-server/src/controllers/auth/logout.ts, desci-server/src/middleware/checkJwt.ts, desci-server/src/utils/sendCookie.ts
=> samesite cookie

desci-server/src/controllers/search/multiQuery.ts, desci-server/src/controllers/search/query.ts, desci-server/src/services/ElasticSearchService.ts
- Removed denormalized works index as we're now aliasing the latest denormalized works index to 'works'
- Added institutions
- Added sources
- Added countries
=> Search Backend Changes

desci-models/package.json, desci-models/src/automerge.ts, desci-repo/package.json, desci-repo/src/services/manifestRepo.ts, desci-repo/src/validators/schema.ts, desci-repo/src/validators/test/schema.spec.ts, desci-repo/yarn.lock, desci-server/package.json, desci-server/src/controllers/nodes/doi.ts, desci-server/src/core/helper.ts, desci-server/src/services/AutomatedMetadata.ts, desci-server/yarn.lock
- Incomplete metadata on first call 
- Updates to manuscript aren't idempotent
- Retry OpenAlex metadata extraction if DOI is retrieved from crossref works api
- Make manuscript update idempotent
- Add `Set Contributors` action to Automerge library and update version number
- Update Desci-repo automerge action handler to support update, add test for new update
=> Metadata extraction fixes and enhancements

desci-server/src/controllers/search/multiQuery.ts, desci-server/src/controllers/search/query.ts, desci-server/src/controllers/search/types.ts, desci-server/src/services/ElasticSearchService.ts
- Changes to support auto complete index
- Switched 'fields' filter to use topics v2, index still requires tweaking
=> Search updates

desci-server/src/controllers/search/query.ts, desci-server/src/services/ElasticSearchService.ts
- Updated 'fields' auto completion index to 'subfields', containing all unique topics.subfield_display_name entries
=> Fields Index

desci-server/src/controllers/search/multiQuery.ts, desci-server/src/services/ElasticSearchService.ts
we were using wrong index before
fixed and also fixed ngram analyzer
=> use correct index and default context novelty sort

docker-compose.dev.yml
- Adds new redis config envvars to resolver service
- Sets up redis healthcheck
- Removes broken grobid healthcheck (`curl` is missing from the base image, docker daemon spams errors)
=> Compose cluster updates

desci-repo/kubernetes/deployment_dev.yaml, desci-repo/kubernetes/deployment_prod.yaml
repo service would have resource issues
increase resources
=> adjust resourcing for repo

desci-repo/src/controllers/nodes/documents.ts, desci-server/src/services/repoService.ts
Closes #503 
- Repo server returns 500 error for empty uuid string
- Sanity check
=> sanity check before attempting to retrieve automerge url doc

desci-server/src/services/auth.ts
logging email token
don't log token
=> sanitize output for email

desci-server/src/services/ElasticSearchService.ts
- Small change to match filter to handle arrays of values
=> Match filter adjustment

.ceramicDev.config.json, ceramic-k8s/ceramic_deployment_dev.yaml, ceramic-k8s/ceramic_deployment_prod.yaml, docker-compose.dev.yml
Enable the metrics scraping endpoints.
Assorted adjustments: 
- fixed dev deployment strat
- bump dev to the anchor healing rc release
=> Ceramic metrics endpoints

desci-server/src/controllers/communities/util.ts, desci-server/src/services/Attestation.ts
reading community radar failed
check publish status with ceramic commitId
=> fix radar query for ceramic streams

desci-server/package.json, desci-server/prisma/schema.prisma, desci-server/src/server.ts, desci-server/yarn.lock
no trace info appearing in sentry
update sentry config to log traces
=> update sentry tracing to log db and http reqs in sentry

desci-server/src/server.ts
sentry config problem
set profileSampleRate
=> apply profile sample rate

desci-server/src/controllers/auth/magic.ts
emails could be variable case
force lowercase
=> fix casing bug in email auth

desci-repo/src/server.ts, desci-server/src/routes/v1/admin/communities/index.ts, desci-server/src/server.ts, docker-compose.test.yml
=> repo sentry config

desci-repo/src/server.ts
=> remove static flag

desci-repo/src/logger.ts
=> fix logger transport

desci-server/src/controllers/search/query.ts, desci-server/src/services/ElasticSearchService.ts
- Improve results for exact matches, new algo for term matching, tries to balance surfacing highly matching queries first above those with higher citations
- Fix boost score function drowning out all results with 0 citations
- Overwrite authors index with the new authors index filled with institution data
- Rank search autocomplete index by citation/works counts to try show more relevant results first
=> Es Changes

desci-server/src/controllers/nodes/publish.ts, desci-server/src/server.ts
=> deprecate old publish flow

desci-server/.gitignore, desci-server/package.json, desci-server/src/controllers/doi/mint.ts, desci-server/src/redisClient.ts, desci-server/src/server.ts, desci-server/src/services/Doi.ts, desci-server/src/services/crossRef/client.ts, desci-server/src/workers/doiSubmissionQueue.ts, desci-server/yarn.lock
- Add a fallback logic for check if pending DOIs have been minted without relying soley on the crossref callback 
- Schedule ping script using cron
- Ping pending DOIs and update job if response is ok
=> Feat: DOI submission queue cron job

desci-repo/src/controllers/nodes/documents.ts, desci-repo/src/lib/PostgresStorageAdapter.ts, desci-repo/src/middleware/ensureApiKey.ts, desci-repo/src/middleware/guard.ts, desci-repo/src/middleware/permissions.ts, desci-repo/src/repo.ts, desci-repo/src/services/manifestRepo.ts, desci-repo/src/services/nodes.ts, desci-repo/src/services/user.ts
- Too much logs emitted on desci-repo recently
=> Clamp down on unnecessary logs

desci-server/src/workers/doiSubmissionQueue.ts
=> dont log for 0 queue pending

desci-server/src/controllers/doi/check.ts, desci-server/src/workers/doiSubmissionQueue.ts
Fix doi lookup, previously doi lookup failed for closed source
=> Fix doi lookup

desci-server/test/integration/community.test.ts
skip community attestation tests temporarily
=> skip tests

desci-server/src/controllers/doi/mint.ts, desci-server/src/templates/emails/DoiMinted.tsx
- email template is buggy
- DOI minting discord notification is sent to the wrong channel
=> fix: email template and discord channel

desci-server/src/controllers/doi/mint.ts
- discord notification for inconclusive doi registration
=> fix one last thing

desci-server/src/services/Doi.ts
fix: fallback to nodeVersions.createdAt in for crossref doi metadata publication date
- fallback to latest nodeVersion createdAt
=> fix: Crossref DOI metadata invalid publicationDate

.gitignore, toolshed/README.md, toolshed/history-debugger/.gitignore, toolshed/history-debugger/README.md, toolshed/history-debugger/package-lock.json, toolshed/history-debugger/package.json, toolshed/history-debugger/src/graph.ts, toolshed/history-debugger/src/history.ts, toolshed/history-debugger/src/index.ts, toolshed/history-debugger/src/markdown.ts
Adds nifty little tool that automatically visualizes publish history from both token and stream. It checks ordering and confirms inclusion of all token updates in the stream.
| Type   | Owner           | ID           |
|--------|-----------------|--------------|
| token  | 0xf0c6957a0caff18d4a18e1ce99b769d20026685e  | 0x30e50caed18dd0291990adf1a8ace1d7a3cec6228319cf79a3e105f8496f6c9e  |
| stream | 0x0f81a4d0553f09767027b4c15d0c374b939cd5f1 | kjzl6kcym7w8y6wtboiio6jmbpml97m04bji4zphyboqhsckz75qg48efglcjox |
| Date | Token (by blocktime) | Stream (by JWT timestamp) |
|------|-------------------|------------------------|
| 2023-12-19T16:30:48.000Z | (0) bafkreigcc2l7aay34i5zeot5wjvpspdpwp6ipfzffs3cnnpbpt7c2gqu6i |            |
| 2023-12-19T16:37:48.000Z | (1) …
=> toolshed: add history visualiser tool

desci-server/src/controllers/admin/debug.ts, desci-server/src/routes/v1/admin/index.ts
- Decoded hex representation of CIDs for easier comparison
- Flipped legacy indexer history to ASC to be consistent with stream history ordering in migration debug portion of the code
=> Debug migration changes

desci-server/src/controllers/doi/mint.ts, desci-server/src/services/crossRef/client.ts, desci-server/src/services/email.ts, desci-server/src/workers/doiSubmissionQueue.ts
- Refactor Crossref retrieve submission success count check: `count > 0`
- Implement email service to make email logic maintainable and well documented
- Send feedback email if DOI is resolved in submission queue checks
=> Email service and DOI submission

desci-server/src/server.ts
=> disable cron temporarily

desci-server/scripts/be-node-dev.sh, desci-server/src/controllers/admin/communities/index.ts, desci-server/src/routes/v1/admin/communities/index.ts, desci-server/src/routes/v1/admin/communities/schema.ts, desci-server/src/services/Attestation.ts, desci-server/test/integration/Attestation.test.ts, desci-server/test/integration/community.test.ts
- Add support for optional entry attestations
=> optional community entry attestations

desci-repo/.gitignore, desci-server/src/controllers/attestations/show.ts, desci-server/src/controllers/nodes/show.ts, desci-server/src/routes/v1/nodes.ts, desci-server/test/integration/Attestation.test.ts, docker-compose.dev.yml
Expose show node attestations from /nodes route
=> expose show node attestations from /nodes route

desci-server/src/server.ts, desci-server/src/workers/doiSubmissionQueue.ts
- cron was disabled to due spam
- use single node lock service to lock processed task job to prevent spam and also update cron config to run every hour
=> Doi queue locking

desci-server/prisma/migrations/20241118075235_/migration.sql, desci-server/prisma/migrations/20241119084420_bookmark_titles/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/doi/check.ts, desci-server/src/controllers/nodes/bookmarks/create.ts, desci-server/src/controllers/nodes/bookmarks/delete.ts, desci-server/src/controllers/nodes/bookmarks/index.ts, desci-server/src/controllers/nodes/openalex.ts, desci-server/src/routes/v1/nodes.ts, desci-server/src/services/BookmarkService.ts, desci-server/src/services/OpenAlexService.ts, desci-server/src/services/node.ts
- Refactored bookmark related controllers
- Added zod input validation
- Extracted core logic out into own service
- Added pagination
- Restructured for flexibility
- Added support for OA/DOI bookmarks
- Refactored open alex metadata fetching by OA/DOI for re-usability
- CONTAINS MIGRATIONS
=> Bookmarks Update

desci-repo/src/services/user.ts
=> Patch middleware crash site

desci-server/src/middleware/permissions.ts, desci-server/src/services/user.ts
=> patch the right user getter method

desci-server/src/middleware/permissions.ts
=> restore return statements

desci-server/src/controllers/doi/index.ts
=> remove stale export

desci-server/src/templates/emails/DoiMinted.tsx
- Email text not properly formatted
=> fix: text spacing to wide

desci-repo/src/repo.ts, desci-repo/src/services/nodes.ts
- Reduce unnecessary logs emitted in Automerge repo share policy
=> Reduce log traces in repo service

desci-server/src/services/Attestation.ts
- attestation `ID -> communityId` bug
- updating attestation doesn't update the `communityEntryAttestation`
- update communityEntryAttestation.attestationVersionId when an attestation is update
- create attestation without ID bug
=> Fix Attestation bugs

.github/workflows/build-server.yaml
- Clear storage ubuntu deployment/test machine in build-server workflow
=> fix: storage issue

desci-server/kubernetes/deployment_dev.yaml, desci-server/kubernetes/deployment_prod.yaml, desci-server/kubernetes/deployment_staging.yaml, desci-server/src/services/repoService.ts, desci-server/test/integration/automerge.test.ts, desci-server/test/integration/data.test.ts, sync-server/src/index.ts
- Static env vars set in k8s config not picked up
=> enforce env flags and vars temporarily

desci-server/src/services/repoService.ts
=> make env flexible

desci-repo/src/controllers/nodes/documents.ts, desci-server/src/services/repoService.ts, desci-server/test/integration/data.test.ts
=> automerge tests failing on dev and passing locally

desci-server/src/controllers/admin/users.ts
- Temporarily Disable pagination
=> temporarily disable pagination for admin users search api

desci-server/prisma/migrations/20250116083416_comment_vote_table/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/attestations/comments.ts, desci-server/src/controllers/nodes/comments.ts, desci-server/src/routes/v1/attestations/schema.ts, desci-server/src/routes/v1/nodes.ts, desci-server/src/services/Attestation.ts, desci-server/test/integration/Attestation.test.ts, desci-server/test/integration/automerge.test.ts
- comments have no voting feature implemented
- Implement feature to support voting for comments resource
=> Implement comment voting feature

sync-server/wrangler.toml
- cloudflare worker sentry integration
=> sync worker sentry integration

sync-server/package.json, sync-server/src/index.ts, sync-server/wrangler.toml, sync-server/yarn.lock
- specify tail on both staging and prod env
=> Worker integration

.github/workflows/deploy-sync-server.yaml, desci-repo/kubernetes/deployment_dev.yaml, desci-repo/kubernetes/deployment_prod.yaml, desci-repo/kubernetes/deployment_staging.yaml, desci-server/kubernetes/deployment_dev.yaml, desci-server/kubernetes/deployment_prod.yaml, desci-server/kubernetes/deployment_staging.yaml
=> Deployment config env update

.github/workflows/deploy-sync-server.yaml
- set worker env secrets for each step
=> set env for each step separately

.github/workflows/deploy-sync-server.yaml
=> fix env in deploy worker script

desci-server/kubernetes/deployment_dev.yaml, desci-server/kubernetes/deployment_prod.yaml, desci-server/kubernetes/deployment_staging.yaml, desci-server/src/services/repoService.ts, sync-server/src/index.ts
=> fix env errors

desci-server/src/controllers/nodes/externalPublications.ts, desci-server/src/scripts/invalidate-redis-cache.ts, desci-server/src/services/openAlex/externalPublication.ts, desci-server/src/services/openAlex/types.ts, desci-server/src/services/repoService.ts
- Fix by pulling data for matching from openAlex
- Add script to prune redis cache by key prefix
=> Enhancement: External publication service (Missing abstract)

desci-server/src/services/crossRef/client.ts, desci-server/src/services/crossRef/externalPublication.ts, desci-server/src/services/openAlex/externalPublication.ts
=> fix crash in crossref client

desci-server/src/controllers/nodes/comments.ts, desci-server/src/routes/v1/attestations/schema.ts, desci-server/src/routes/v1/nodes.ts, desci-server/src/services/Attestation.ts, desci-server/test/integration/Attestation.test.ts
=> Refactor: changes to comments api and add traces

desci-server/prisma/migrations/20250203135951_comment_reply/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/attestations/comments.ts, desci-server/src/controllers/nodes/comments.ts, desci-server/src/routes/v1/attestations/index.ts, desci-server/src/routes/v1/attestations/schema.ts, desci-server/src/services/Attestation.ts, desci-server/test/integration/Attestation.test.ts
- Update post comments api to add support for comment replies
- Update getComments Api to retrieve replies using cursor based pagination
- Write integration tests for comments/replies feature
=> Comment reply

.env.example, desci-server/kubernetes/deployment_dev.yaml, desci-server/kubernetes/deployment_prod.yaml, desci-server/kubernetes/deployment_staging.yaml, desci-server/src/controllers/admin/analytics.ts, desci-server/src/middleware/permissions.ts, desci-server/src/routes/v1/admin/index.ts, desci-server/src/services/crossRef/client.ts, desci-server/src/services/crossRef/types/summary.ts, desci-server/src/services/crossRef/types/works.ts, desci-server/src/services/interactionLog.ts, desci-server/src/services/user.ts, desci-server/src/types/ProcessEnv.d.ts
- Implement user analytics api for Orcid and non- users
- Implement apis for probing into new and active users (view and raw data)
- Integrate Orcid public profile to analytics data
=> Feat: Orcid admin stats and implement apis to display users in stats

desci-server/prisma/migrations/20250226042357_node_like/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/nodes/likes.ts, desci-server/src/middleware/authorisation.ts, desci-server/src/routes/v1/nodes.ts, desci-server/src/services/node.ts, desci-server/test/integration/nodes.test.ts
- Feature: users can like/appreciate a node
- Add database schema migration
- Implement new api with strict validation 
- Add new Nodes service for likes feature
- Run database migration after deployment
=> Feat: Node likes API implementation

desci-server/src/controllers/admin/analytics.ts
- Analytics csv report doesn't include new orcid stats  in the new admin dashboard
=> Feat: reflect Orcid stats in user analytics report

desci-server/src/controllers/attestations/recommendations.ts, desci-server/src/services/Attestation.ts
- Recommended attestations Api returns incomplete data
- fix getRecommendedAttestations query function
=> fix: recommended attestations query

desci-server/package.json, desci-server/src/controllers/nodes/externalPublications.ts, desci-server/src/scripts/pruneExternalPublications.ts, desci-server/src/services/crossRef/externalPublication.ts, desci-server/yarn.lock
- add logic to prune redis cache 
=> add redis cache prune to external pub script

desci-server/src/controllers/admin/nodes.ts, desci-server/src/controllers/nodes/externalPublications.ts, desci-server/src/controllers/nodes/publish.ts, desci-server/src/routes/v1/admin/index.ts, desci-server/src/routes/v1/admin/nodes.ts, desci-server/src/scripts/invalidate-redis-cache.ts, desci-server/src/services/crossRef/client.ts, desci-server/src/services/crossRef/externalPublication.ts, desci-server/src/services/externalPublications.ts, desci-server/src/services/openAlex/externalPublication.ts
Closes https://github.com/desci-labs/nodes-web-v2/issues/1064
- Properly link external publications to published nodes
- Test with a lot of published articles/journals on desci nodes
- Integrate article recommender api as fallback
- Refactor object matching scoring logic to reduce minimum threshold based on number of available matching fields on target object
- Integrate Article recommender API
- Implement Admin Apis for debugging external pub service
- Refactor controllers and publish hooks
=> External pub service upgrade

desci-server/src/controllers/admin/analytics.ts
- Add Separate column for Orcid user stats in  csv report
=> Separate Orcid users into new row

desci-server/src/config/index.ts, desci-server/src/controllers/nodes/createDpid.ts, desci-server/src/controllers/nodes/publish.ts, desci-server/src/services/nodeManager.ts, desci-server/src/theGraph.ts, docker-compose.dev.yml
- graph node crashes on M3 Max due to database unavailabilty
- Link graph node using docker host `host.docker.internal` instead of container name
- make sure `PG_HOST=host.docker.internal` is set in your local `.env` file
=> Local pub debug (Graph node crashes)

desci-server/package.json, desci-server/src/controllers/admin/analytics.ts, desci-server/src/routes/v1/admin/index.ts, desci-server/src/services/interactionLog.ts, desci-server/src/services/nodeManager.ts, desci-server/src/services/user.ts, desci-server/yarn.lock
=> feat: analytics aggregation api

desci-server/src/controllers/admin/analytics.ts
- Analytics query can take a long time to respond if the range is about a year and aggregated daily
- Minimize calls to database when requesting for CSV document of already processed analytics data
- Parallelize calls to analytics services
- Cache aggregated data for 24 hours and reuse in CSV data queries
=> Improve api performance

desci-server/prisma/migrations/20250318133217_community_submission_schema/migration.sql, desci-server/prisma/schema.prisma, desci-server/src/controllers/communities/submissions.ts, desci-server/src/core/ApiResponse.ts, desci-server/src/routes/v1/communities/index.ts, desci-server/src/routes/v1/communities/submissions-schema.ts, desci-server/src/routes/v1/communities/submissions.ts, desci-server/src/routes/v1/index.ts, desci-server/src/routes/v1/users.ts, desci-server/src/services/Communities.ts, desci-server/test/integration/community.test.ts
Closes #842 
- Implement Apis and functionalities for Community submissions
=> feat: submissions api

desci-server/src/controllers/communities/feed.ts, desci-server/src/controllers/communities/submissions.ts, desci-server/src/routes/v1/users.ts, desci-server/src/services/Communities.ts, desci-server/test/integration/community.test.ts
Closes #842 
- update submission details api authorisation 
-  community details api
=> Submission details api authorisation and community details api

desci-server/src/controllers/communities/submissions.ts, desci-server/src/routes/v1/communities/submissions.ts
=> fix: create submissions api

desci-server/src/controllers/admin/analytics.ts, desci-server/src/routes/v1/admin/index.ts
- Admin users should be able to export/download users data in csv format
- Add support for exporting analytics data using a query parameter
=> feat: add support for exporting user/active-users analytics data in csv

desci-server/src/controllers/communities/submissions.ts, desci-server/src/routes/v1/communities/submissions.ts, desci-server/src/services/Communities.ts
Closes #842 
- Imlement Api to cancel user subscriptions, 
- fix: undefined bug in createSubmission
=> Cancelation of community submission

toolshed/vault-tools/README.md, toolshed/vault-tools/secretSearch.sh
Convenient vault search util I've had locally for a while
=> toolshed: add `secretSearch.sh` script

desci-server/src/controllers/communities/submissions.ts, desci-server/src/routes/v1/communities/submissions.ts, desci-server/src/services/email.ts, desci-server/src/templates/emails/RejectSubmission.tsx
Closes #842
- Rejection email formatting
=> fix: reason for rejection not sent with email

desci-server/src/controllers/admin/analytics.ts
- Issue with admin dashboard analytics chart returning incomplete data for the endDate
-
=> Analytics bug pro

desci-server/src/controllers/communities/submissions.ts, desci-server/src/utils/manifest.ts
- Fix crash when retrieving node manifest using it's cid
=> Decline submissions api 

desci-server/src/controllers/nodes/comments.ts, desci-server/src/controllers/nodes/likes.ts, desci-server/src/middleware/authorisation.ts, desci-server/src/routes/v1/nodes.ts
- Make comments and likes api partially public to anon users
=> Make Get comments and likes api public with restrictions

desci-server/package.json, desci-server/src/controllers/admin/analytics.ts, desci-server/src/controllers/admin/schema.ts, desci-server/src/controllers/communities/submissions.ts, desci-server/src/docs/analytics.ts, desci-server/src/docs/communities.ts, desci-server/src/docs/openai.ts, desci-server/src/docs/submissions.ts, desci-server/src/routes/v1/admin/index.ts, desci-server/src/routes/v1/communities/submissions-schema.ts, desci-server/src/server.ts, desci-server/src/swagger.ts, desci-server/src/swagger_output.json, desci-server/yarn.lock
- Setup API documentation
- Document some major Api resources and do the rest incrementally
=> API documentation for Nodes backend

desci-server/src/controllers/communities/submissions.ts
=> fix: broken import

desci-server/package.json, desci-server/src/config/index.ts, desci-server/src/controllers/authors/index.ts, desci-server/src/routes/v1/authors.ts, desci-server/src/routes/v1/index.ts, desci-server/src/scripts/invalidate-redis-cache.ts, desci-server/src/services/crossRef/externalPublication.ts, desci-server/src/services/index.ts, desci-server/src/services/openAlex/client.ts, desci-server/src/services/openAlex/types.ts, desci-server/yarn.lock
- Implement Apis for author profiles and works
=> Author profile and Works Api

desci-server/src/controllers/authors/index.ts
=> enable caching for author apis

desci-server/package.json, desci-server/src/controllers/admin/analytics.ts, desci-server/src/controllers/admin/schema.ts, desci-server/src/controllers/communities/submissions.ts, desci-server/src/docs/analytics.ts, desci-server/src/docs/communities.ts, desci-server/src/docs/openai.ts, desci-server/src/docs/submissions.ts, desci-server/src/routes/v1/admin/index.ts, desci-server/src/routes/v1/communities/submissions-schema.ts, desci-server/src/server.ts, desci-server/src/swagger.ts, desci-server/src/swagger_output.json, desci-server/yarn.lock
=> Revert "Revert "API documentation for Nodes backend""

desci-server/src/controllers/authors/index.ts, desci-server/src/docs/authors.ts, desci-server/src/docs/openai.ts
- Add documentation for Authors api
=> Document authors api

desci-server/src/controllers/authors/index.ts, desci-server/src/docs/authors.ts, desci-server/src/routes/v1/authors.ts
Closes [#1194](https://github.com/desci-labs/nodes-web-v2/issues/1194)
- feat: Implement api to retrieve an authors published nodes
- Add proper documentation
=> API to retrieve published nodes of public author profiles

desci-server/src/services/ElasticSearchService.ts
Find an ES indexed native work by dpid, requested by @shadrach-tayo
=> ES query for DPID lookup

desci-server/src/controllers/admin/analytics.ts, desci-server/src/services/interactionLog.ts, desci-server/src/services/nodeManager.ts, desci-server/src/services/user.ts, desci-server/src/utils/clock.ts, desci-server/test/integration/analytics.test.ts, desci-server/test/integration/community.test.ts, desci-server/test/integration/nodes.test.ts, desci-server/test/integration/util.test.ts, docker-compose.test.yml
admin analytics overview - today was off
fix time and time diff / time zone calculation
=> Fix tests fix analytics

desci-server/test/integration/analytics.test.ts, desci-server/test/integration/util.test.ts
- Date-time util test is not stable and blocks PR
=> disable for now

desci-server/src/controllers/doi/check.ts, desci-server/src/docs/doi.ts, desci-server/src/docs/openai.ts, desci-server/src/services/OpenAlexService.ts
- Return author's ORCID in retrieve DOI api
- Document both api routes
=> Author ORCID

desci-server/src/controllers/authors/index.ts, desci-server/src/docs/authors.ts, desci-server/src/routes/v1/authors.ts, desci-server/src/services/openAlex/client.ts
- Author profile and works api support for OpenAlex ID along side ORCID as ID parameter
- fix cache miss bug
=> add support for openalex identifier in author apis id param

desci-server/src/controllers/search/query.ts, desci-server/src/controllers/search/types.ts, desci-server/src/routes/v1/search.ts
Add monthly api for browsing nodes originated
=> Add monthly api

desci-server/test/integration/analytics.test.ts
=> fix analytic tests

desci-server/package.json, desci-server/src/controllers/authors/index.ts, desci-server/src/controllers/search/query.ts, desci-server/src/services/ElasticSearchService.ts, desci-server/yarn.lock
- Test Research object browse by month api
- Fix bug in Author works api
=> fix: error in author works api

desci-server/src/controllers/doi/check.ts, desci-server/src/controllers/nodes/openalex.ts, desci-server/src/docs/openai.ts, desci-server/src/docs/openalex.ts, desci-server/src/services/OpenAlexService.ts
Update openalex work api and retrieve doi api to include author names orcid, and openalex id
=> Openalex and Doi api updates

desci-server/src/controllers/authors/index.ts, desci-server/src/services/crossRef/client.ts, desci-server/src/services/openAlex/client.ts
=> fix: error in author api

desci-server/src/controllers/admin/analytics.ts, desci-server/src/services/interactionLog.ts, desci-server/src/services/user.ts
fixes problem with error in user report download
=> fix download user report

desci-server/src/controllers/authors/index.ts, desci-server/src/controllers/authors/transformer.ts, desci-server/src/controllers/authors/types.ts
- Author api crashes when orcid is null
=> fix: author api crashes (no orcid)

desci-server/src/controllers/authors/index.ts, desci-server/src/docs/authors.ts, desci-server/src/routes/v1/authors.ts, desci-server/src/services/OpenAlexService.ts, desci-server/src/services/crossRef/client.ts
- Paginate queries 
- add text search for filtering
- fix potential bug in `crossref#getProfileExperience`
=> CoAuthors api optimisation 

desci-server/src/controllers/authors/index.ts, desci-server/src/services/OpenAlexService.ts
=> fix: db query param bug and cache invalidation issue on search query

desci-server/src/services/OpenAlexService.ts
=> push a rebuild

desci-server/src/controllers/authors/index.ts, desci-server/src/controllers/authors/types.ts, desci-server/src/docs/authors.ts, desci-server/src/services/OpenAlexService.ts, desci-server/src/services/crossRef/client.ts
Closes #928 
- Implement and Expose author Indices via api
=> Author Indices calculation

desci-server/src/services/crossRef/externalPublication.ts
=> reduce crossref match score minimum threshold

desci-server/src/controllers/communities/submissions.ts, desci-server/src/scripts/query-nodes-by-attestation.ts
fix audit script plus pagination for community endpoint
=> page default 10, update cli

desci-server/src/controllers/communities/submissions.ts, desci-server/src/services/Communities.ts
add totalcount to submission api
=> add totalcount to submission api 
