desci-labs/nodes

- desci-server/src/controllers/data/rename.ts
Renaming a file was losing its connected component if it had one
Logic error, fixed
> FIX: Rename bug

- desci-server/src/controllers/data/rename.ts
- desci-server/src/controllers/data/update.ts
- desci-server/src/controllers/data/utils.ts
External URLs only supported code
Renaming a file wouldn't be in sync with its component, as file name !== component name, adding support for this on the frontend would cause a race condition between the dag being updated and the component name being changed in the manifest.
Added pdf support for external URLs
Added rename component support on dag rename controller
> Data/Extend external url support, add rename component ability to renaming files

- desci-server/src/services/ipfs.ts
Backend filters out certain files in tree gen functions, this can lead to issues consuming those functions in some scenarios
Removed filtering in tree generation functions, raw trees are returned
> Minor Fix/Remove tree filtering

- desci-server/src/controllers/data/update.ts
- desci-server/src/middleware/upgradeManifest.ts
- desci-server/src/routes/v1/data.ts
Predefined component subtype assignment was failing
Duplicate path check was failing if component added through manual add flow (non dnd)
Case consistency of subtype keyword fixed the type assignment problem
Drag and drop browser uploads vs modal browser uploads resulted in a path discrepancy being forwarded to the backend, added a check to see ensure there's a preceding slash in the path to ensure path consistency between both upload methods.
> Bug fixes/Update Data

- dockerDev.sh
Some small issues prevented `dockerDev.sh` from behaving nicely on linux, and some errors were a bit tricky to debug. E.g. missing implicit dependencies, broken `NVM_DIR` check, etc.
- Adds sanity-preserving flags (`set -euo pipefail`)
- Explicitly check for dependency availability
- Simplify `nvm` command inclusion
N/A
N/A
> Fix setup issues in `dockerDev.sh`

- desci-server/src/controllers/data/update.ts
- desci-server/src/services/ipfs.ts
Updating a DAG with an external CID containing a DAG that failed to resolve all contents within the DAG was unhandled, the assumption was made that if the DAG resolved, all contents within would resolve also - false.
Added extra handling around the edge case where an external CID DAG resolves but its contents fail to resolve, failing to build the tree.
> External CID DAG resolution failing handling

- desci-server/package.json
when developing on desci-server,  ts-node-dev would unreliably restart the server after code change
add `--watch` flag to package json for `yarn dev`
use as normal
> fix watch mode

- desci-server/package.json
need more transparency to what ts-node-dev is doing / waiting for server to start
add --debug flag to package.json for desci-server
use as normal, can see debug output
> debug output for ts-node-dev

- desci-server/prisma/migrations/20230719172545_add_orcid_cache/migration.sql
- desci-server/prisma/migrations/20230719181835_fix_orcid_profile_model/migration.sql
- desci-server/prisma/migrations/20230719193032_add_json_profile/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/controllers/proxy/orcidProfile.ts
- desci-server/src/controllers/proxy/orcidQuery.ts
- desci-server/src/routes/v1/index.ts
- desci-server/src/routes/v1/services.ts
Closes #99
Add caching of orcid profiles to prevent spamming the API
Added a route to query the orcid api for an orcids profile, caching the result in psql, cache set at a daily ttl.
Added an option to invalidate the cache and force a refresh sooner than the daily ttl
Rate limited the refresh to prevent spamming the ORCID API
Call to
`/v1/services/orcid/profile/:orcidId`
Append "refresh=true" query param to invalidate the cache immediately
`v1/services/orcid/profile/:orcidId?refresh=true`
> Orcid Profile Caching

- desci-server/src/controllers/data/retrieve.ts
Closes #103 
Invalid routes for pubTree api not unhandled
Fixed crash from invalid route when using pubTree api
> Bug Fix: Invalid data route causing crash

- desci-server/src/controllers/data/retrieve.ts
- desci-server/src/scripts/dataRefDoctor.ts
- desci-server/src/services/ipfs.ts
- desci-server/src/services/nodeManager.ts
- desci-server/src/utils/dataRefTools.ts
- desci-server/src/utils/driveUtils.ts
- desci-server/test/integration/data.test.ts
Closes #107
- There are two different environments where nodes are currently published; nodes prod, and nodes dev, both don't share the same dbs, when external data is linked in a node, it is required to be marked before generating trees, if we don't know a node contains external data then the tree generation will fail, public data references need to be backfilled on either prod/dev for them to be able to work interchangeably.
- The function to generate a external CID map, marking which data is external only utilized data refs, not public refs, this could lead to a potential issue of external data being deleted in a draft, and the tree not being able to be generated in previous published versions, or future versions.
- Fixed the backfilling script by adding an option to provide a working …
> Improve backfilling for nodes with external data

- desci-server/package.json
- desci-server/src/scripts/invalidate-redis-cache.ts
No easy way to invalidate all cached keys related to a given node uuid
Added a script to invalidate all cache keys for published nodes by their uuid
Run the following in desci-server whilst it's running:
OPERATION=invalidateByUuid NODE_UUID=nOdEUuiD npm run script:invalidate-redis-cache
> Added redis cache invalidation script

- desci-models/src/trees/treeTools.ts
- desci-models/src/trees/treeTypes.ts
Closes #98
- Lack of information of a directories contents without potential manual deep traversal of that dir.
- Expanded the tree generation API to include a property on dirs that reflects the contained components within them, and their aggregate counts.
> Expand metadata for dirs

- desci-server/src/controllers/data/diff.ts
- Bug where a 0 size diff prevented the controller from returning
- Cluttered logging for fail condition
- Fixed check on size diff
- Improved logging output to be less cluttered and show more relevant info for debugging
> Bug fix: Diff controller failing to return on diffless size

- desci-server/src/controllers/data/updateExternalCid.ts
- desci-server/src/services/ipfs.ts
- desci-server/src/utils/driveUtils.ts
- Bug where empty dirs were being passed in a function that expected non empty dirs
- On resolution failure, failing CID isn't logged
- Fixed empty dir bug
- Improved logging to know which CID failed to resolve
> Tree improvements

- desci-server/src/utils/diffUtils.ts
- When 'removed' diff entries are pruned, it results in an empty result.
- Wrong map was being used to prune removed entries, fixed.
> Bug-fix: Fix diff pruning

- desci-server/src/controllers/data/update.ts
- desci-server/src/services/ipfs.ts
- desci-server/src/utils.ts
- Leak in stream data flow causing OOM issues when adding repos
- One point in the repo upload flow was pushing all file contents into a buffer, should be fixed.
Needs live testing
> Memory fix for repo data uploads

- desci-server/prisma/migrations/20230904170249_add_failed_attempts/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/controllers/auth/magic.ts
- desci-server/src/middleware/checkJwt.ts
- desci-server/src/middleware/ensureUser.ts
- desci-server/src/services/auth.ts
- desci-server/test/integration/auth.test.ts
- For V2 that's using SSR the bearer token wouldn't be passed on first loads.
- Few vulnerabilities
- Added cookie auth
- Mitigated potential auth vulnerabilities
- Added tests to test a few core auth flows
**CONTAINS MIGRATIONS**
Extra considerations: 
- Consider using CSRF tokens since cookies are now valid
- httpOnly property enabled but still sending back bearer for backwards compatibility still gives exposure to auth XSS, consider removing bearer token header in the future
> Auth Cookies for SSR

- desci-server/src/controllers/auth/magic.ts
- Dev cookie available on prod
- Dev cookie doesn't save in a localhost with tls disabled frontend environment
- Restrict the dev cookie to only be usable in the dev testing API backend
- Secure flag disabled for the dev cookie
> Dev Cookie fixes

- desci-server/src/controllers/auth/magic.ts
- Cookie properties for a cookie with the same name are cumulative, not overwritten
- Explicitly overwrote the cookie property needed for the dev token, instead of commenting it out
> Dev cookie fix

- desci-server/src/controllers/data/updateExternalCid.ts
- A check in the code to ensure external cids being imported were data components created a bug that caused a situation where external DAG's were pinned, though not added to the research object's DAG.
- No good reason to restrict external CIDs to be data only, no issue with allowing the component type to be flexible.
- Simply removing that single check alleviates all issues.
> Fix external CID import bug

- desci-models/src/ResearchObject.ts
Closes: https://github.com/desci-labs/nodes-web-v2/issues/227
- We need to simplify annotation types to support different kinds of annotations in the future and support text pdf annotations
- Simplify and Switch ResearchObjectComponentAnnotation to declaration to interface
- Add specific interface for PdfAnnotations that extends the Base Annotation interface
> RFC: Annotations interface model update

- desci-models/src/ResearchObject.ts
- 'image' property in the manifest was confusing, it was never used either.
- Renamed to 'coverImage', before we start using it.
> Cover image models

- desci-server/package.json
- desci-server/prisma/migrations/20231108232618_default_drive_gb/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/scripts/increase-base-drive-storage.ts
- package-lock.json
- upgrade users to default 100gb storage
- update user table defaults
- add script to upgrade users under a target amount of gb storage
run migrations to set default to 100gb
run `npm run script:increase-base-drive-storage 100` to upgrade all existing users to 100gb
> update drive storage space default

- desci-server/src/scripts/dataRefDoctor.ts
Cloning a node is useful for testing purposes, at the moment no functionality like so exists.
Added a script to clone draft mode nodes.
Create a fresh empty node, copy its UUID and run the script
`OPERATION=clonePrivateNode NODE_UUID=noDeUuiD. NEW_NODE_UUID=nEwnoDeUuiD2. npm run script:fix-data-refs`
> Clone node script

- desci-server/src/services/data/processing.ts
- Upper case extensions weren't being recognized
- Parsed all extensions to lower case before checking the type map
> Fix case bug for component type detection

- desci-server/src/controllers/nodes/list.ts
- desci-server/src/controllers/nodes/share.ts
- desci-server/src/controllers/nodes/show.ts
- Soft deleted nodes could still be resolved
- Prevented deleted nodes from being resolved in most common routes
> Prevent resolution of soft deleted nodes

- desci-models/src/ResearchObject.ts
- No field on the manifest for a global node description
- Added a description string field on the manifest to be used as an overall node description/summary, this will serve as a stopgap until we get the block editor refined, this field may then be migrated to either a string or IPLD uri
> Add global description to RO models

- .vscode/settings.json
- desci-server/src/controllers/auth/magic.ts
- desci-server/src/controllers/nodes/draftUpdate.ts
- desci-server/src/lib/PostgresStorageAdapter.ts
- desci-server/src/repo.ts
- after switching to auto merge, node titles don't update right away
- we cache titles in database to avoid fetching document data, create a document change handler that updates the database after a title change
> Fix node title using automerge document change hooks

- desci-server/src/controllers/data/delete.ts
- desci-server/src/controllers/data/move.ts
- desci-server/src/controllers/data/rename.ts
- desci-server/src/controllers/nodes/documents.ts
- desci-server/src/controllers/nodes/prepublish.ts
- desci-server/src/services/data/externalCidProcessing.ts
- desci-server/src/services/data/externalUrlProcessing.ts
- desci-server/src/services/data/processing.ts
- desci-server/src/services/draftTrees.ts
- desci-server/src/services/manifestRepo.ts
- desci-server/src/types/documents.ts
- With the draft data tree changes, we can no longer rely on a data bucket CID to know if the file tree has changed.
- Add a drive clock to the automerge document that reflects the last updated item in the nodes draft tree.
- WIP Still needs all instances covered where a draft tree change may occur
> Automerge Drive Clock

- desci-server/src/controllers/nodes/list.ts
- desci-server/src/repo.ts
- Collection API missing node cover data
- Automerge not updating node cover in the db
- Collection endpoint now also returns NodeCover data
- Automerge updates to the latest NodeCover in the db
> Cover api fixes

- .ceramicDev.config.json
- .env.example
- README.md
- bootstrapCeramic.sh
- desci-contracts/scripts/seed.sh
- desci-server/prisma/migrations/20240110092031_add_ceramic_streamid_to_node/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/controllers/nodes/prepublish.ts
- desci-server/src/controllers/nodes/publish.ts
- desci-server/src/services/nodeManager.ts
- docker-compose.dev.yml
Adds a Ceramic node to the local dev cluster, supporting a feature toggled publishing flow in nodes-web-v2.
- New docker compose service called `ceramic`. It uses the same dev postgres database as the rest.
- Necessary version bump of kubo
- Prisma migration to keep track of streamIDs along with the node UUID.
- Changes to `publish` and `prepublish` to keep track of the above
- Should be fully backward compatible :crossed_fingers: 
- To opt in, set the corresponding environment variable as demonstrated in `.env.example`.
- Finally, run `bootstrapCeramic.sh`, which will deploy models from [@desci-labs/desci-codex](https://github.com/desci-labs/desci-codex). This is a bit annoying, because it needs to run when the cluster is already up, making it hard to integrate into the make scripts …
> Add Ceramic node in dev cluster

- desci-server/src/controllers/data/retrieve.ts
- manifestCid is a deprecated field used in old draft tree fetching logic, it has become deprecated as of the drive tree update, leaving the logic in there was prone to cause some issues for some developers if the incorrect manifestCid was passed in as a param.
- Removed the outdated logic that was no longer used, should prevent issues caused by the API being called with an incorrect manifestCid.
- Route remains the same with the :manifestCid still included as a route param, this can be removed as long as all APIs using this route are updated, whilst doing that we need to keep in mind the :shareId param being used in the same route for the private share functionality.
> Hotfix: retrieveTree pass

- nodes-lib/package.json
- nodes-lib/src/api.ts
- nodes-lib/src/publish.ts
- nodes-lib/src/routes.ts
- nodes-lib/test/root.spec.ts
It was very easy to screw up an endpoint call by using the wrong method, missing some parameter, etc. Implemented more declarative endpoint registry which specs the method, payload, and response which is quiiite neat.
> nodes-lib: declarative endpoint definitions

- .env.example
- desci-server/kubernetes/deployment.yaml
- desci-server/kubernetes/deployment_dev.yaml
- desci-server/prisma/migrations/20240229065702_add_publish_worker_table/migration.sql
- desci-server/prisma/migrations/20240229071713_add_publish_node_action_type/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/controllers/nodes/publish.ts
- desci-server/src/server.ts
- desci-server/src/services/interactionLog.ts
- desci-server/src/theGraph.ts
- desci-server/src/workers/publish.ts
- Implement simple task queue using postgress
- Implement worker to process task queue and trigger publish depending on transaction status
- Separate `/publish` from `publishTaskProcessor`
UPDATE .env to add correct `ETHEREUM_RPC_URL` value
> feat: implement async publishing using simple task queue on progress

- nodes-lib/package.json
- nodes-lib/src/api.ts
My waterproof path conversion missed the humble `/` as a definition for drive root. Hence, it fell through and set `root/` which broke stuff :)
> nodelib: hotfix issue with absolute path conversion

- desci-models/package.json
- desci-models/src/ResearchObject.ts
- desci-models/src/transformers/RoCrateTransformer.ts
- Models lack a UID to pin an entry to, only ORCIDs/Google Scholar ID would be a fair alternative, though it's not a required field for contributors.
- Add the id field on a contributor entry to hold a UUID
> Contributors model update

- nodes-lib/package-lock.json
- nodes-lib/package.json
- nodes-lib/src/api.ts
- nodes-lib/src/chain.ts
- nodes-lib/src/codex.ts
- nodes-lib/src/config/chain.ts
- nodes-lib/src/config/index.ts
- nodes-lib/src/errors.ts
- nodes-lib/src/index.ts
- nodes-lib/src/publish.ts
- nodes-lib/src/routes.ts
- nodes-lib/test/root.spec.ts
This PR adds a new failure mode on publish, a special error for catching the case where signing address and RO token owner differs. This allows apps to react nicely before having to sign a TX which may fail with opaque errors instead.
Also adds capabilities for passing an (optional) `DIDSession` authorized DID to the `publishDraftNode` function, which avoids forcing a SIWE signature inside `nodes-lib` to authenticate for Ceramic. This triggers a second metamask window which we can now skip. (cc @shadrach-tayo )
There is also a getter for the resource ID's needed for the DID authorization, namely `getResources`. (cc @shadrach-tayo )
> nodes-lib token ownership check & DIDSession support

- ceramic-k8s/ceramic_deployment_dev.yaml
- ceramic-k8s/ceramic_deployment_prod.yaml
The dev node only talks to the Clay testnet, for production we need one using the Ceramic mainnet.
Add a deployment spec for the production node
Part from the config that follows below, note these things:
1. Needs a companion IPFS node (the URL `public-ceramic-ipfs-prod-service-internal` used in config below does not yet exist)
2. A new, empty persistent disk for the `state-store`
The node config vault secrets require some tweaking in `/desci-server/production/db` compared to `/desci-server/dev/db`:
1. `.Data.ceramic_rpc` needs to be set to an Ethereum **mainnet** endpoint
2. `.Data.ceramic_cas_pkey` needs to be set to a new secret (sent to @hubsmoke in TG)
4. `.Data.ceramic_url` needs to point to a new, empty database marked for ceramic mainnet
There is the full config for reference: …
> Ceramic prod deployment

- desci-server/package.json
- desci-server/prisma/migrations/20240417110758_add_protected_column_to_attestations_table/migration.sql
- desci-server/prisma/migrations/20240417141710_add_verified_image_column_to_attestation_table/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/scripts/be-node-dev.sh
- desci-server/src/controllers/attestations/recommendations.ts
- desci-server/src/controllers/attestations/verification.ts
- desci-server/src/data/communities.json
- desci-server/src/routes/v1/attestations/index.ts
- desci-server/src/routes/v1/communities/index.ts
- desci-server/src/scripts/seed-community-members.ts
- desci-server/src/scripts/seed-social-data.ts
- desci-server/src/services/Attestation.ts
- desci-server/src/services/Communities.ts
- desci-server/test/integration/Attestation.test.ts
- desci-server/test/integration/community.test.ts
```
For desci foundation we are implementing two protected attestations (open data, open code), this is the overleaf blog post. These are by desci foundation, and can only be validated by members. Desci foundation also has a curator function where they set attestations as curation criteria (currently scientific manuscript and desci fund). The curation criteria can be any subset of all existing attestations (meaning they can also contain attestations that were created and/or can be validated by other communities). Protected attestations created by a community may be used as curation criteria by that same community but they don’t have to. 
Like Carla said, the DeSci Foundation will validate claims for "Open Data" and "Open Code" attestations. When we validate these attestations, they will …
```
> Protected Attestations/Guarded Validation

- desci-server/src/controllers/attestations/verification.ts
- desci-server/src/services/orcid.ts
- desci-server/src/services/user.ts
fixes:
- prevent storing duplicate orcid  authToken for same user
- update orcid work record after protected claim is unverified
- add feature to refresh and update orcid authToken before use in orcid service
> Orcid authtoken refresh

- nodes-lib/README.md
- nodes-lib/package.json
- nodes-lib/src/config/chain.ts
- nodes-lib/src/config/index.ts
Wasn't possible to use staging API's
Add `staging` config, re-using chain config from `dev`
Updating to `nodes-lib@0.0.6` and using `setNodesLibConfig(NODESLIB_CONFIGS.staging)` will activate this configuration.
> nodes-lib: support staging environment with dev contracts

- desci-server/src/templates/emails/BaseProvider.tsx
- desci-server/src/templates/emails/MagicCode.tsx
- desci-server/src/templates/emails/MainLayout.tsx
Switched to a PNG version of the logo. Curious to know how the blend mode works on dark BG, but can't be worse than a broken image :D
Learnings:
1. Gmail refuses to render SVG under basically any circumstances
2. Gmail refuses base64 image embeds under any circumstances
3. The reason is their gigantic image cache system can't work them
Resolves #388
> server: fix email logos

- desci-server/kubernetes/deployment_dev.yaml
- desci-server/kubernetes/deployment_prod.yaml
- desci-server/kubernetes/deployment_staging.yaml
- desci-server/src/services/orcid.ts
Reverts desci-labs/nodes#344
Interpolating a value that doesn't exist in the env renders a syntactically incorrect config file, putting pods that upgrade in a crash loop by preventing the entire environment to load. When this happens, the repo "worker" process throws and crashes the container.
```json
{
"err": {
"message": "[REPO SERVICE]: env.REPO_SERVER_URL or env.REPO_SERVICE_SECRET_KEY missing",
"stack": "Error: [REPO SERVICE]: env.REPO_SERVER_URL or env.REPO_SERVICE_SECRET_KEY missing\n    at new RepoService (file:///app/dist/services/repoService.js:10:19)\n    at file:///app/dist/services/repoService.js:92:21\n    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)\n    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)\n    at async loadESM …
```
> Revert "DPID url config "

- desci-server/src/controllers/attestations/verification.ts
- desci-server/src/controllers/communities/guard.ts
- desci-server/src/controllers/communities/index.ts
- desci-server/src/routes/v1/attestations/index.ts
- desci-server/src/routes/v1/attestations/schema.ts
- desci-server/src/routes/v1/communities/index.ts
- desci-server/src/routes/v1/communities/schema.ts
- desci-server/src/services/Attestation.ts
- desci-server/test/integration/Attestation.test.ts
- Restrict protected attestations review/comments to authorised validators only
- Add guard api to check if auth user has community member authorisation
> Guard API (Protected attestations)

- desci-server/src/services/data/externalUrlProcessing.ts
- desci-server/src/services/data/processing.ts
Partially addresses #336
- PDF determination was done by seeing if the URL ends with .pdf, this logic caused pdf components that would be supported within the app to be uploaded as external URLs instead.
- A head call is done on the external URL and the mimeType is checked to see if it could be a PDF, this expands the scope of links that can be correctly used to import PDFs externally via URL, however this still doesn't work for some links that don't directly send the user to the PDF download and instead redirect users to their own PDF renderer (like google links) as their mimeTypes would instead be text/html, these types will probably need special handling for commonly used services.
> Smarter external url processing for PDFs

- desci-server/src/workers/publish.ts
Publish worker suddenly stopped running
Identified an error 520 around the same time, thinking that this exception caused publish worker to exit. Surrounding with try-catch and logging
> Hotfix publish worker

- desci-server/scripts/be-node-dev.sh
- desci-server/scripts/import-ipfs-content.sh
- desci-server/src/logger.ts
- desci-server/src/middleware/authorisation.ts
- desci-server/src/server.ts
- when logging to betterstack we have no ability to tell which log items were related or which user triggered them
secondarily: when developing locally certain images were expected to be on IPFS public resolver, but when deving locally we use a private IPFS node which has no access
- add traceId to all requests
- make any other log lines read from AsyncLocalStorage to also include traceId
- log the userId if logged in
- send X-Desci-Trace-Id in response for debugging failed requests in the wild
secondarily: - add import-ipfs-content.sh script to fix broken images when local dev
no action required
> add traceIds to logs and also fix ipfs image imports

- desci-repo/.env.example
- desci-repo/kubernetes/deployment_dev.yaml
- desci-repo/kubernetes/deployment_prod.yaml
- desci-repo/kubernetes/deployment_staging.yaml
- desci-repo/src/middleware/permissions.ts
- desci-server/src/controllers/auth/logout.ts
- desci-server/src/middleware/permissions.ts
- desci-server/src/utils/sendCookie.ts
frontend PR https://github.com/desci-labs/nodes-web-v2/pull/761
make cookie auth isolated per environment, preventing collisions across nodes-api-dev nodes-api-staging and nodes-api
this fixes the bug users experience when navigating between nodes prod and nodes dev
> make cookie auth isolated per environment

- desci-server/src/controllers/attestations/claims.ts
- desci-server/src/routes/v1/attestations/index.ts
- desci-server/src/services/Attestation.ts
when attestations are optional they are not automatically claim in CLAIM ALL workflow, this makes them all claimed
> hotfix: add support to claim all optional attestations

- desci-server/src/controllers/nodes/createDpid.ts
- nodes-lib/package.json
- nodes-lib/src/config/chain.ts
- nodes-lib/src/config/index.ts
Ensures our friend the staging environment uses external production environments, so it matches up with the resolver :medical_symbol:
> Fixes so staging uses production environments

- desci-media-isolated/.env.example
- desci-media-isolated/kubernetes/deployment_dev.yaml
- desci-media-isolated/kubernetes/deployment_prod.yaml
- desci-media-isolated/kubernetes/deployment_staging.yaml
- desci-media-isolated/src/services/pdf.ts
- desci-server/src/services/PublishPackage.ts
- DPID resolver urls were hardcoded for prepub generations, leading to covers generated in dev containing prod URLs
- Added an env in the media server to set the env depending on the environment
> Fix dpid urls

- desci-server/src/controllers/auth/magic.ts
- desci-server/src/controllers/nodes/checkNodeAccess.ts
- desci-server/src/services/Contributors.ts
- desci-server/src/services/user.ts
- If a user doesn't use the shared link in their email they're unable to verify their contribution
- Added contribution inheritance logic in signup flow, when a user registers they inherit all contributions that used their email/orcid, allowing them to access their shared nodes from profile and verifying their contributions.
Relies on the priv share fixes being merged in:
FE: https://github.com/desci-labs/nodes-web-v2/pull/811
BE: https://github.com/desci-labs/nodes/pull/431
> Inherit contributions

- desci-server/src/controllers/attestations/claims.ts
Check deferredAttestation email entries before revoking claims to be able to find them using the claimId
> Unclaim attestations removing deferredEmail entry fix

- desci-server/prisma/migrations/20240808190859_revert_deferred_table/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/controllers/attestations/claims.ts
- desci-server/src/services/PublishServices.ts
- The Attestation relation in the deferredEmail table in the initial PR was correct, reverted the table back to this state
- Reverted the changed functions, fixed the one broken function that was taking in the wrong type of attestation id.
Includes migrations
> DeferredEmail table revert, correct fix applied

- desci-server/src/controllers/raw/versions.ts
- desci-server/src/theGraph.ts
Was unaware that some really old nodes were missing the database, should have worked anyway but due to a bug in filtering UUID's not so much  :bug:
> server: fix history lookup for nodes missing in the database

- desci-server/src/client.ts
- desci-server/src/controllers/nodes/bookmarks/index.ts
- desci-server/src/controllers/nodes/checkNodeAccess.ts
- desci-server/src/controllers/nodes/contributions/getUserContributions.ts
- desci-server/src/controllers/nodes/getPublishedNodeStats.ts
- desci-server/src/controllers/nodes/getPublishedNodes.ts
- desci-server/src/controllers/nodes/list.ts
- desci-server/src/controllers/nodes/sharedNodes.ts
- desci-server/src/controllers/nodes/show.ts
- desci-server/src/services/Contributors.ts
- desci-server/src/services/data/processing.ts
- desci-server/src/services/manifestRepo.ts
- desci-server/src/theGraph.ts
- desci-server/src/utils.ts
- desci-server/src/utils/driveUtils.ts
- desci-server/src/utils/manifest.ts
Changes the implementation of (almost) all node enumeration routes in desci-server to avoid (needlessly) using `getIndexedResearchObjects`, as this is too slow for the frequency we're hitting it. It's also causing a ton of traffic on the ceramic node, and when we don't even need the results this is a bit pointless.
It does change the return types a bit in the cases where the webapp anyway wasn't using the fields that are more complicated to derive. Simplification and speedup in both ends :eyes: 
Even locally, this branch is a quite massive speedup for me :zap::dancing_men::zap: 
Also fixes a bug in `getBlockTime` which could be the one I've been chasing, throwing in some extra debug logging just in case though so we can track it.
Companion webapp PR: …
> Speedup node queries ⚡

- desci-contracts/package.json
- desci-contracts/yarn.lock
- desci-server/package.json
- desci-server/yarn.lock
- nodes-lib/package-lock.json
- nodes-lib/package.json
- Bumped desci-contracts to 0.2.7 to fix dpid-registry-alias contract address for local dev environment, should now match that of a fresh deterministic build
- Bumped nodes-lib to 0.1.0 to update the desci-contracts package used
Local dev environments need to be reset to enable publish functionalities to work
> Desci-contracts bump

- desci-contracts/package.json
- desci-contracts/yarn.lock
- desci-server/nodemon.json
- desci-server/package.json
- desci-server/src/controllers/nodes/getPublishedNodes.ts
- desci-server/src/controllers/nodes/preparePublishPackage.ts
- desci-server/src/services/PublishPackage.ts
- desci-server/src/theGraph.ts
- desci-server/yarn.lock
- nodes-lib/package-lock.json
- nodes-lib/package.json
- Prepub generation was iffy post ceramic changes
- Issue was dpid retrieval was done using the old fashioned technique, updated to use the db and fallback on the manifest
- Improved robustness of prepub gen in a rerun situation post publish, this should prevent issues if the manifestCid shifts at the time of request, not matching that of a published manifestCid.
> Ceramic prepub fixes

- desci-server/src/config/index.ts
- desci-server/src/controllers/admin/debug.ts
- desci-server/src/controllers/admin/index.ts
- desci-server/src/controllers/nodes/byDpid.ts
- desci-server/src/controllers/nodes/createDpid.ts
- desci-server/src/routes/v1/admin.ts
- desci-server/src/services/ceramic.ts
- desci-server/src/services/chain.ts
Adds `/v1/admin/debug/:uuid` and `/v1/admin/debug` routes to automatically sanity check nodes. 
Does this stuff, among other things:
- validates anchoring
- show anchor timing
- compares db/stream/index versions
- tries resolving dpid alias
- verifies all published manifests have a PublicDataRef
The non-uuid route takes args to search in time over recent activity/node creation, super useful but will result in a ton of activity all over the cluster if not used carefully :p
```ts
type DebugAllNodesQueryParams = {
fromDate?: string,
toDate?: string,
timeColumn?: "createdAt" | "updatedAt",
};
```
> Node debug route

- desci-server/src/controllers/doi/check.ts
- desci-server/src/controllers/nodes/doi.ts
- desci-server/src/routes/v1/nodes.ts
- desci-server/src/services/Doi.ts
- Retrieve Doi routes was refactored to resolve openAlex doi and broke some features on the frontend
- `DoiService#checkMintability` crashes due to skipped check
- Add separate api for retrieving auth node Doi details
- Fix invariants in `DoiService#checkMintability`
> Doi Api routes

- Dockerfile
- desci-server/scripts/import-ipfs-content.sh
- desci-server/src/controllers/admin/debug.ts
- desci-server/src/logger.ts
- dockerDev.sh
Also filters on first/last publish instead, as this is makes more sense than node create/update timestamps
Also fixes bug where `import-ipfs-content.sh` can fail if image hasn't been rebuilt in a while, as it tries to install `curl`/`wget` but the package URL in `apt` may 404. We should anyway have dependencies declared in the image :ok_hand:
> Debug route only investigates published nodes

- desci-server/src/controllers/attestations/claims.ts
- desci-server/src/controllers/nodes/doi.ts
- desci-server/src/core/ApiError.ts
- desci-server/src/core/ApiResponse.ts
- Descriptive error message in case extraction not possible
- Add new error type to support unprocessable entity,
-  Throw error in automateDoiManuscript if no metadata was extracted, 
- Sanitize response object to remove empty message field
> Metadata extraction & Api enhancement

- desci-server/src/controllers/raw/resolve.ts
- desci-server/src/services/ceramic.ts
- desci-server/src/theGraph.ts
- desci-server/src/utils/driveUtils.ts
`getTreeAndFill` super sluggish due to missing anchors leading to spamming repeated history lookups.
`getTreeAndFill` just needs timestamps, which we can get from the raw stream state, not having to resolve the individual versions at all.
Additionally, by using [`SyncOpts.NEVER_SYNC`](https://developers.ceramic.network/reference/typescript/enums/_ceramicnetwork_common.SyncOptions.html)  (or `?sync=2` on the HTTP route) when loading the stream, we tell the node we only care about what it currently knows. This prevents it to going to check libp2p pubsub for new updates, which is pointless because we know exactly what commit ID we are looking for.
> server: fix sluggish lookups

- desci-server/src/controllers/nodes/publish.ts
- desci-server/src/services/PublishServices.ts
- Defer emails was broken in a recent change to make it more efficient, it was passing an invalid DPID due to it being moved into the same promise array that would resolve the dpid value asynchronously along with sending the email, moving it back out solved the issue.
- Fixed 'Invalid Date' prepubs, in a local dev environment, ceramic anchoring is done instantly, and so the commitId is available at the time of it being requested in prepub, however in a live environment, anchoring takes some time so the timestamp was unable to be resolved during distribution pdf generation time, falling back on Date.now() fixes this issue
- Switched the getBlocktime method used when generating prepub dist pdfs to use the new more efficient function 'getTimeForTxOrCommits', utilizing the ceramic raw log for …
> Prepub + Defer Emails fix

- docker-compose.dev.yml
- docker-compose.media.yml
- docker-compose.test.yml
- docker-compose.yml
Using the policy `always` is suboptimal for two reasons:
- it covers up if a service exits 0 on errors, as this does not signal to the docker/kubernetes daemons that the service failed
- it forces automatically restarting all containers after a reboot / docker daemon restart, leading to unexpected results when running `./dockerDev.sh`
> compose: use on-failure restart policy for compose services

- desci-server/src/controllers/search/multiQuery.ts
- desci-server/src/controllers/search/query.ts
- desci-server/src/controllers/search/types.ts
- desci-server/src/services/ElasticSearchService.ts
Previously I wasn't able to copy/paste an ES query direct from logs to ES Dev Console
Now we format the final query in the logs, for copy/paste ease
> fix how we log ES queries

- ceramic-k8s/ceramic_deployment_dev.yaml
- ceramic-k8s/ceramic_deployment_prod.yaml
- docker-compose.dev.yml
- Bump the ceramic node to 6.4.0 to get a couple of fixes
- This is a major because new nodes default to using RECON for tip synchronization, but existing node can continue to use kubo for p2p comms and tip sync.
- Change the compose cluster versions of kubo to match the ones we are running in the live envs.
Switching around between versions 0.23-0.29 should be fine as they use the same version of the IPFS repo:
https://github.com/ipfs/fs-repo-migrations?tab=readme-ov-file#when-should-i-migrate
> compose: sync kubo with live deployments, bump ceramic to 6.4.0

- nodes-lib/package.json
- nodes-lib/src/codex.ts
- nodes-lib/src/util/signing.ts
When switching chains, the optimism sepolia chainID in the app config went from 11155111 to 11155420. This caused the commit JWS validation to fail in `js-did/dids`, as the fully qualified CAIP addresses aren't equal: https://github.com/ceramicnetwork/js-did/blob/main/packages/dids/src/did.ts#L407-L410
(`did:pkh:eip155:11155111:0xec..." !== "did:pkh:eip155:11155420:0xec...`)
Override the chainID with whatever the registered stream controller has, if we had an existing stream to append to. 
We should figure out a sane default, as it's unclear whether we need to set any particular chainID at all in these messages.
- Bump `@desci-labs/nodes-lib@0.0.11-rc1` in nodes-web-v2
> nodes-lib: override DID EIP155 namespace in SIWE message to match stream controller

- nodes-lib/package.json
- nodes-lib/src/util/signing.ts
This change was already published and installed to nodes-web-v2 as part of a hotfix last friday.
To prevent DID's forking history from using whatever chainID the wallet currently provides when creating the ceramic CACAO, we continue to use the eth sepolia one until we have a better solution.
> nodes-lib: force sep eth chainid in CACAO unless overridden

- desci-server/src/controllers/nodes/byDpid.ts
- desci-server/src/controllers/nodes/checkNodeAccess.ts
Webapp state needed the `ceramicStream` field to fix the publish permission check. The access check is used to check if a node is published, and is run early in the node loading process on the frontend.
Together with the other publish information, `/v1/nodes/access/:uuid` returns the `dpidAlias` and `ceramicStream` on record.
N/A
N/A
> server: include stream & dpid with other public info in checkNodeAccess

- desci-server/src/services/orcid.ts
- desci-server/src/theGraph.ts
Closes #504 
https://app.zenhub.com/workspaces/desci-nodes-6634c157eb5d5e1212342833/issues/gh/desci-labs/nodes/504
- Orcid Nodes dataset work record dpid path
- Clear orcid work record if no claims are found
> Fix Orcid Work record invalid Dpid url

- .env.example
- desci-server/src/config/index.ts
- desci-server/src/services/fixDpid.ts
- desci-server/src/theGraph.ts
- docker-compose.dev.yml
- dockerDev.sh
Closes #537
Tiny fixes:
- Allow using the faster `fnm` instead of `nvm`, if available
- Add `.env.example` docs on configuring the resolver
- Use the `develop` image for the compose resolver, as `latest` is the production build
The görli -> sepolia migration created dupes in the version history for migrated entries. We have previously filtered these our in the frontend, but it's better if the app doesn't need to know about this every time it's using the results.
If the configured `THEGRAPH_API_URL` is the dev sepolia one, do a deduplication pass on the returned versions.
N/A
N/A
> server: dedupe dev subgraph responses

- desci-server/kubernetes/deployment_dev.yaml
- desci-server/kubernetes/deployment_prod.yaml
- desci-server/kubernetes/deployment_staging.yaml
- desci-server/src/server.ts
Logs spammy af, about half a million per hour just from the probes 🥴 This is costing us proper pesetas in Betterstack.
1. Switch to using the dedicated probe route `/readyz`
2. Handler returns responses early on the `/readyz`, avoiding any meaningful work on the request
3.  Disable `pino-http` autologging of requests on this route
N/A
N/A
> server: use `/readyz` for probes and squelch logging on that route

- desci-repo/src/controllers/nodes/documents.ts
- desci-repo/src/logger.ts
- desci-server/src/controllers/communities/util.ts
- desci-server/src/controllers/data/rename.ts
- desci-server/src/controllers/data/retrieve.ts
- desci-server/src/controllers/nodes/bookmarks/index.ts
- desci-server/src/controllers/nodes/draftCreate.ts
- desci-server/src/controllers/nodes/draftUpdate.ts
- desci-server/src/controllers/nodes/prepublish.ts
- desci-server/src/controllers/nodes/sharedNodes.ts
- desci-server/src/controllers/nodes/show.ts
- desci-server/src/services/data/externalUrlProcessing.ts
- desci-server/src/services/data/processing.ts
- desci-server/src/services/manifestRepo.ts
- desci-server/src/services/nodeManager.ts
- desci-server/src/services/repoService.ts
- desci-server/test/integration/Attestation.test.ts
- Calls to create draft, get node draft manifest and show nodes are slow and sometimes cause the tests to crash/fail
- Remove database calls for nodes in repo service
- In `/createDraft` cache draft node metadata for a minute to serve hot calls (non-blocking)
- Refactor `nodes#show` controller and optimize calls for retrieving draft manifest
- Refactor reposervice to pass documentId to `getDraftDocument` and `getDraftManifest` methods
- In Repo server, fast track calls to`getLatestNodeManifest` by attempting to use `documentId` query if found and fallback to uuid if not
- All calls to `getDraftManifest()` within the app are automatically optimized
- Optimize `retrieveTree` api by switching `getLatestManifestFromNode` in favor of `showNodeDraftManifest`
- Implement a new nodeManager …
> API Optimisation and enhancement

- desci-repo/kubernetes/deployment_dev.yaml
- desci-repo/kubernetes/deployment_prod.yaml
- desci-repo/kubernetes/deployment_staging.yaml
- desci-server/src/controllers/admin/debug.ts
>2M loglines per day from repo service
@shadrach-tayo did a pass on logs, skipping trace and debug by default should be okay.
> repo-server: reduce default logginess

- desci-server/nodemon.json
- desci-server/src/controllers/admin/debug.ts
- Some migrations were problematic, no easy way to identify these
- Added migration debugging info to the node debug route
- Checks if the legacy RO owner and the stream controller match
- Checks if all versions present in the legacy RO were successfully migrated
- Standard use of the debug route, provides extra info for streams that were migrated indicating any faults.
> Debug Ceramic Migration

- desci-server/src/services/NotificationService.ts
- Send dotless node uuid in notification payloads
- Add generic user name for profiles without names in notifications to prevent 'null has commented...'
> Minor notification bug fixes

- desci-server/src/services/ElasticSearchService.ts
Closes https://github.com/desci-labs/capybara-feedback/issues/927
- Autocomplete results were overly affected by citation/works counts in the latest update, this buried some results that were most relevant to the query string but didn't have much citation/search count.
- Changed the query to prioritize text matches, adding  a threshold match for flexibility, greatly reduced impact of citation/works counts, and its effectively now used as a tie breaker between identical matches, fixes the reported bug.
Ideally we also reindex the autocomplete index with ASCII folding to not trip up the searches with diacritics in queries
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html
> Es autocomplete improvements

- desci-server/src/routes/v1/nodes.ts
- Make Nodes DOI retrieve api public
This is because Published nodes with DOI need to show it on the Nodes home even when the client is not authenticated.
> make node doi query api public

- desci-server/src/controllers/nodes/doi.ts
- desci-server/src/services/AutomatedMetadata.ts
- Contributor entries have no unique uuid https://nodes.desci.com/dpid/282/contributors which breaks verification/invite flow
- Add generated unique id to each author entries from metadata extraction
> fix: author id is missing from metadata extraction automation

- nodes-lib/.vscode/launch.json
- nodes-lib/test/root.spec.ts
- To rule out the current migration logic having issues we need tests that focus on the ordering of versions for legacy published nodes -> ceramic nodes
- Added tests for multiple version legacy nodes migrating to a ceramic stream
> Debug Migration order bug

- desci-server/src/controllers/attestations/verification.ts
- desci-server/src/services/orcid.ts
- Orcid work record integration breaks due to legacy dpid use
- fallback on node dpidAlias
> fix: Legacy dpid check breaks orcid work record integration

- desci-repo/.gitignore
- desci-server/package.json
- desci-server/src/scripts/prune-auth-tokens.ts
- Implement a script to prune revoked orcid tokens
```bash
export DRY_RUN=1
yarn script:prune-auth-tokens
```
> script: Orcid prune auth tokens

- desci-server/prisma/migrations/20241125141101_user_unseen_notif_count/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/controllers/notifications/create.ts
- desci-server/src/controllers/notifications/notificationCount.ts
- desci-server/src/controllers/notifications/update.ts
- desci-server/src/routes/v1/notifications.ts
- desci-server/src/services/NotificationService.ts
- desci-server/test/integration/notifications.test.ts
Closes # https://github.com/desci-labs/nodes-web-v2/issues/1021
- The logic for the seen/dismissing notifications has changed, these 2 actions are decoupled
- Added new endpoints for maintaining the unseen count of notifications, fetching/resetting
- DB Migrations needed!
> Notifications adjustments

- desci-server/src/controllers/auth/login.ts
Api calls to `/auth/check` api crashes
- add missing return statement
> fix: setting response header being sent to client

- desci-server/src/controllers/nodes/publish.ts
- nodes-lib/package-lock.json
- nodes-lib/package.json
- nodes-lib/src/api.ts
- nodes-lib/test/root.spec.ts
- Make DOI registration opt-in during  prepublication submission
- Make DOI registration opt-in during prepub flow
- Update nodes-lib to accept args
- Update desci publish api make DOI minting optional
> Optional DOI registration for submission packages

- .env.example
- .env.test
- .github/workflows/deploy-sync-server.yaml
- desci-repo/src/controllers/nodes/documents.ts
- desci-server/kubernetes/deployment_dev.yaml
- desci-server/kubernetes/deployment_prod.yaml
- desci-server/kubernetes/deployment_staging.yaml
- desci-server/src/services/repoService.ts
- desci-server/test/integration/automerge.test.ts
- desci-server/test/integration/data.test.ts
- sync-server/package.json
- sync-server/src/automerge-repo-storage-postgres/PostgresStorageAdapter.ts
- sync-server/src/index.ts
- sync-server/src/lib/schema.ts
- sync-server/src/manifestRepo.ts
- sync-server/wrangler.toml
- sync-server/yarn.lock
- Migrate critical repo apis affecting Automerge documents to Cloudflare workers
- Put all new features behind feature flags
- This makes actions like `creating` and `updating` a research object document faster and resilient
- Removes the repo server middleman and reduces risk of request failing in this new architecture
> offload repo and automerge apis to cloudflare workers

- desci-server/test/integration/automerge.test.ts
- disable automerge tests for now (the pass in PR and fail in build-server workflow)
> disable automerge unit tests

- desci-server/src/controllers/attestations/recommendations.ts
- desci-server/src/routes/v1/attestations/index.ts
- desci-server/src/routes/v1/attestations/schema.ts
- desci-server/src/services/Attestation.ts
- We need a way to search attestations as the list keeps growing
- Extend the `attestations/suggestions/all` api to support search queries
- Limit response to `5` if not search query is passed to request
> Feat: Implement attestations search Api

- desci-server/package.json
- desci-server/prisma/migrations/20250108131055_community_radar_entry/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/controllers/attestations/claims.ts
- desci-server/src/controllers/communities/feed.ts
- desci-server/src/controllers/communities/radar.ts
- desci-server/src/controllers/communities/types.ts
- desci-server/src/controllers/communities/util.ts
- desci-server/src/routes/v1/communities/index.ts
- desci-server/src/routes/v1/communities/schema.ts
- desci-server/src/scripts/backfill-radar.ts
- desci-server/src/services/Attestation.ts
- desci-server/src/services/Communities.ts
- desci-server/test/integration/Attestation.test.ts
Closes #722 
```
- Call communityService.getCommunityRadar:
- Largeish 4 table join to get node attestations et al
- Takes between 1 and >2.5s depending on db cache
- async map attestationService.getNodeEngagementSignals over all nodes:
- aggregate engagement signals for each node with a largeish join query
- attach the aggregate signals to the node objects
- map resolveLatestNode over all nodes:
- node discovery query
- node versions query
- fetch manifest over IPFS
- fall back to repo manifest fetch
- sort resulting (node+engagement+manifest) combo by engagements and claim timestamps
```
```
Community radar API performance improvements
Create a new table called community-radar-entry(nodes + community joins)
When a node joins a community radar we add an entry to this table
when a node …
```
> Community radar/feed API performance optimisation

- desci-server/package.json
- desci-server/prisma/migrations/20250108131055_community_radar_entry/migration.sql
- desci-server/prisma/migrations/20250110112721_add_date_to_annotation/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/controllers/attestations/claims.ts
- desci-server/src/controllers/communities/feed.ts
- desci-server/src/controllers/communities/radar.ts
- desci-server/src/controllers/communities/types.ts
- desci-server/src/controllers/communities/util.ts
- desci-server/src/routes/v1/communities/index.ts
- desci-server/src/routes/v1/communities/schema.ts
- desci-server/src/scripts/backfill-radar.ts
- desci-server/src/services/Attestation.ts
- desci-server/src/services/Communities.ts
- desci-server/test/integration/Attestation.test.ts
Add date field to annotations 
- Update Annotation schema to add `createdAt` and `updatedAt` fields
> Dated comments

- desci-server/src/controllers/attestations/claims.ts
- desci-server/src/controllers/attestations/verification.ts
- desci-server/src/controllers/communities/feed.ts
- desci-server/src/controllers/communities/radar.ts
- desci-server/src/controllers/communities/util.ts
- desci-server/src/controllers/nodes/feed.ts
- desci-server/src/routes/v1/communities/index.ts
- desci-server/src/routes/v1/communities/schema.ts
- desci-server/src/services/Communities.ts
- desci-server/test/integration/Attestation.test.ts
- Enhancements to Radar/Feed Apis to improve frontend UX
- Enhance api structures and types returned to frontend
- Redis caching of some social data values
- Optimise database queries to avoid multiple round trips 
> Radar api enhancements and optimisation

- desci-server/src/controllers/admin/users.ts
- desci-server/src/middleware/ensureAdmin.ts
- desci-server/src/middleware/permissions.ts
- desci-server/src/routes/v1/admin/index.ts
- desci-server/src/routes/v1/admin/users/index.ts
- docker-compose.dev.yml
- Implement users admin api for search and role toggling
> Admin privileges and User Admin API

- desci-server/src/controllers/nodes/comments.ts
- desci-server/src/services/Communities.ts
- Quick fix for the bug in title
- Strict null check on database call response
> Bug when revoking claimed attestation and pruning node from communityRadarEntry

- desci-repo/src/lib/automerge-repo-network-websocket/PartykitWsServerAdapter.ts
- desci-repo/src/repo.ts
- desci-repo/src/server.ts
- desci-server/package.json
- desci-server/prisma/migrations/20250124124412_is_verified_publication/migration.sql
- desci-server/prisma/migrations/20250127072323_externalpub_verified_at/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/controllers/nodes/externalPublications.ts
- desci-server/src/controllers/nodes/publish.ts
- desci-server/src/routes/v1/nodes.ts
- desci-server/src/scripts/pruneExternalPublications.ts
- desci-server/src/services/crossRef/definitions.ts
- desci-server/src/services/crossRef/externalPublication.ts
- desci-server/src/templates/emails/ExternalPublications.tsx
- desci-server/src/templates/emails/utils/emailRenderer.tsx
- sync-server/src/index.ts
- Dispatch external publication check and Send email notification to publisher after a publish flow
- Cache external pub check
> feat: cache external pub, send email notifications and return default

- desci-models/package.json
- desci-models/src/transformers/RoCrateTransformer.ts
- desci-models/tests/example-data/exampleNode.json
- desci-models/tests/example-data/exampleNodeToRoCrate.json
- desci-models/tests/transformers/RoCrateTransformer.test.ts
The generated HTTP gateway links for drive tree components doesn't resolve on ipfs.io
> models: use ipfs.desci.com in RO-Crate transformer gateway URLs

- desci-server/src/controllers/doi/check.ts
- Duplicate http `response.send` accounts for `>1.1k` errors from sentry report
[Sentry Issue](https://desci-labs.sentry.io/issues/6076488528/?notification_uuid=9d43d283-ebda-4f2a-8772-2a4761e135f3&project=6619754&referrer=weekly_report)
> fix: sending duplicate internal error response

- desci-server/prisma/migrations/20250320105957_doi_queue_attempts/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/services/Doi.ts
- desci-server/src/workers/doiSubmissionQueue.ts
- We have a lot of failed DOI resolution attempts from calls to DOIs that might never be resolved in the DOI submission queue
- Add a database column to track the number of attempts
- Mark DOI status as failed after 5 attempts
> Add resolution attempts to DOI submission queue to limit retries

- desci-server/src/controllers/nodes/getPublishedNodes.ts
- desci-server/src/services/Attestation.ts
- desci-server/src/utils/manifest.ts
- Published nodes list api uses draft manifest title 
- Emails notifying members of badges claim is outdated, it looks like this: https://nodes-dev.desci.com/dpid/1091/v1/attestations/open-data Instead it should look like this: https://nodes-dev.desci.com/dpid/1091/v1/badges
> Published nodes api & email link

- desci-models/package.json
- desci-models/src/actions.ts
- desci-server/package.json
- desci-server/prisma/migrations/20250326110833_rejection_reason/migration.sql
- desci-server/prisma/schema.prisma
- desci-server/src/controllers/attestations/show.ts
- desci-server/src/controllers/communities/submissions.ts
- desci-server/src/routes/v1/communities/submissions-schema.ts
- desci-server/src/services/Attestation.ts
- desci-server/src/services/Communities.ts
- desci-server/src/services/email.ts
- desci-server/src/templates/emails/RejectSubmission.tsx
- desci-server/src/templates/emails/utils/emailRenderer.tsx
- desci-server/src/utils/manifest.ts
- desci-server/yarn.lock
Closes #842 
- Update to endpoint to add message before rejecting community submission
- Extend payload for community object(add slug & communityMembers array) in attestation endpoint
- Update api logic for rejection submission
- Add rejection reason to db schema
- Add email service for notifying users of rejection
- Update attestations endpoint response shape include slug and members)
- Run database migrations
> Submission Rejection reason

- desci-server/src/controllers/admin/analytics.ts
- I'm seeing something weird in our admin overview: The first page shows right now that we already have 6 new users today. But in the analytics view, the number of new users for today and yesterday is zero. Other charts in that view also report 0 for the last two days. I'm guessing something is broken with the analytics charts.  Can you guys check this out, please? 
- pull data from start to end of day of the date range
> fix: analytics time range

- desci-server/src/controllers/communities/submissions.ts
- desci-server/src/routes/v1/communities/index.ts
- when not logged in, none of community research page loads
- fix: remove user auth requirement for community submission api route
> Community get submissions api route auth removal

- desci-server/src/controllers/communities/list.ts
Communities list response is bloated sometimes unnecessarily taking up to 1-2s to load
add a skip querystring option
http://localhost:5420/v1/communities/list?skip=description,members,keywords,metrics
add skip param to web requests that don't need all fields
> skip fields in community list for faster / smaller response
